export type NewsSourceKind = 'gaming' | 'technology' | 'science' | 'ai' | 'streaming' | 'asia-gaming'

export interface NewsSource {
  id: string
  name: string
  kind: NewsSourceKind
  region: string
  url: string
  rss?: string
  language: 'es' | 'en' | 'multi'
  attribution: string
  status: 'ready' | 'manual-review' | 'api-needed'
  notes: string
}

export const NEWS_SOURCE_GROUPS: Record<NewsSourceKind, string> = {
  gaming: 'Gaming',
  technology: 'Tecnología',
  science: 'Ciencia',
  ai: 'IA',
  streaming: 'Streaming',
  'asia-gaming': 'Asia Gaming',
}

export const trustedNewsSources: NewsSource[] = [
  {
    id: 'ign',
    name: 'IGN',
    kind: 'gaming',
    region: 'Global',
    url: 'https://www.ign.com',
    rss: 'https://feeds.ign.com/ign/all',
    language: 'en',
    attribution: 'Titular, resumen corto y enlace a IGN. No copiar artículos completos.',
    status: 'manual-review',
    notes: 'Fuente internacional para gaming, trailers, reviews y lanzamientos.',
  },
  {
    id: 'gamespot',
    name: 'GameSpot',
    kind: 'gaming',
    region: 'Global',
    url: 'https://www.gamespot.com',
    rss: 'https://www.gamespot.com/feeds/mashup/',
    language: 'en',
    attribution: 'Mostrar enlace original y usar solo extracto propio.',
    status: 'manual-review',
    notes: 'Útil para lanzamientos, análisis y novedades AAA/indie.',
  },
  {
    id: '3djuegos',
    name: '3DJuegos',
    kind: 'gaming',
    region: 'España/LATAM',
    url: 'https://www.3djuegos.com',
    language: 'es',
    attribution: 'Citar fuente y enlazar. Usar como disparador para nota propia.',
    status: 'manual-review',
    notes: 'Muy útil para comunidad hispanohablante.',
  },
  {
    id: 'xataka',
    name: 'Xataka',
    kind: 'technology',
    region: 'España/LATAM',
    url: 'https://www.xataka.com',
    language: 'es',
    attribution: 'Citar fuente y enlazar. Crear análisis propio XETHKIOZ.',
    status: 'manual-review',
    notes: 'Tecnología, ciencia aplicada, IA y cultura digital.',
  },
  {
    id: 'the-verge',
    name: 'The Verge',
    kind: 'technology',
    region: 'Global',
    url: 'https://www.theverge.com',
    rss: 'https://www.theverge.com/rss/index.xml',
    language: 'en',
    attribution: 'Usar titular como referencia, resumen propio y enlace original.',
    status: 'manual-review',
    notes: 'Tech, hardware, plataformas, IA y cultura digital.',
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Technology Review',
    kind: 'ai',
    region: 'Global',
    url: 'https://www.technologyreview.com',
    rss: 'https://www.technologyreview.com/feed/',
    language: 'en',
    attribution: 'Fuente premium. Resumir con atribución y no copiar texto.',
    status: 'manual-review',
    notes: 'IA, innovación, sociedad y futuro tecnológico.',
  },
  {
    id: 'nasa',
    name: 'NASA',
    kind: 'science',
    region: 'Global',
    url: 'https://www.nasa.gov',
    rss: 'https://www.nasa.gov/news-release/feed/',
    language: 'en',
    attribution: 'Fuente pública oficial. Mantener enlace y contexto.',
    status: 'ready',
    notes: 'Espacio, misiones, ciencia y tecnología espacial.',
  },
  {
    id: 'science-daily',
    name: 'ScienceDaily',
    kind: 'science',
    region: 'Global',
    url: 'https://www.sciencedaily.com',
    rss: 'https://www.sciencedaily.com/rss/top.xml',
    language: 'en',
    attribution: 'Usar solo referencia y enlace original. Reescritura propia.',
    status: 'manual-review',
    notes: 'Ciencia general, medicina, espacio y descubrimientos.',
  },
  {
    id: 'twitch-blog',
    name: 'Twitch Blog',
    kind: 'streaming',
    region: 'Global',
    url: 'https://blog.twitch.tv',
    language: 'en',
    attribution: 'Fuente oficial. Citar y enlazar.',
    status: 'manual-review',
    notes: 'Cambios de plataforma, herramientas y monetización.',
  },
  {
    id: 'youtube-blog',
    name: 'YouTube Official Blog',
    kind: 'streaming',
    region: 'Global',
    url: 'https://blog.youtube',
    language: 'en',
    attribution: 'Fuente oficial. Citar y enlazar.',
    status: 'manual-review',
    notes: 'Shorts, directos, creadores y monetización.',
  },
  {
    id: 'inven-global',
    name: 'Inven Global',
    kind: 'asia-gaming',
    region: 'Asia/Global',
    url: 'https://www.invenglobal.com',
    language: 'en',
    attribution: 'Citar fuente y enlazar; útil para esports asiáticos.',
    status: 'manual-review',
    notes: 'Esports, LoL, gaming coreano y cultura competitiva.',
  },
  {
    id: 'gematsu',
    name: 'Gematsu',
    kind: 'asia-gaming',
    region: 'Japón/Global',
    url: 'https://www.gematsu.com',
    rss: 'https://www.gematsu.com/feed',
    language: 'en',
    attribution: 'Citar fuente y enlazar. Resumen propio.',
    status: 'manual-review',
    notes: 'Juegos japoneses, anuncios, RPG, trailers y consola.',
  },
  {
    id: 'pc-gamer',
    name: 'PC Gamer',
    kind: 'gaming',
    region: 'Global',
    url: 'https://www.pcgamer.com',
    rss: 'https://www.pcgamer.com/rss/',
    language: 'en',
    attribution: 'Usar como referencia de agenda y enlazar al original.',
    status: 'manual-review',
    notes: 'PC gaming, hardware gamer, mods, Steam y cultura PC.',
  },
  {
    id: 'arxiv-cs-ai',
    name: 'arXiv CS.AI',
    kind: 'ai',
    region: 'Global',
    url: 'https://arxiv.org/list/cs.AI/recent',
    rss: 'https://rss.arxiv.org/rss/cs.AI',
    language: 'en',
    attribution: 'Marcar como preprint. No presentar como evidencia definitiva.',
    status: 'ready',
    notes: 'Investigación IA preliminar para AI Lab y Science Lab con cautela editorial.',
  },
  {
    id: 'nature-news',
    name: 'Nature News',
    kind: 'science',
    region: 'Global',
    url: 'https://www.nature.com/news',
    rss: 'https://www.nature.com/nature.rss',
    language: 'en',
    attribution: 'Fuente científica editorial. Citar, resumir y enlazar.',
    status: 'manual-review',
    notes: 'Ciencia, papers, política científica y descubrimientos relevantes.',
  },
  {
    id: 'eurogamer',
    name: 'Eurogamer',
    kind: 'gaming',
    region: 'Europa/Global',
    url: 'https://www.eurogamer.net',
    rss: 'https://www.eurogamer.net/feed',
    language: 'en',
    attribution: 'Referencia externa con enlace. Crear análisis propio XETHKIOZ.',
    status: 'manual-review',
    notes: 'Reviews, industria gamer, lanzamientos y análisis europeo.',
  },
]

export const dailyUpdateRules = [
  'No copiar notas completas de terceros.',
  'Toda noticia externa debe enlazar a la fuente original.',
  'XETHKIOZ publica resumen propio, contexto y opinión editorial.',
  'Las noticias sensibles deben marcar diferencia entre hecho, rumor y análisis.',
  'Las fuentes se revisan manualmente antes de activar automatización.',
]
