import type { PublicNewsArticle, PublicNewsCategory } from './publicNewsService'

const PUBLISHED_AT = '2026-07-01T11:30:00.000Z'

export const curatedExternalNews: PublicNewsArticle[] = [
  {
    id: 'curated-gaming-gta-vi-2026-07-01',
    slug: 'radar-gaming-gta-vi-reservas-digital',
    title: 'Radar Gaming · GTA VI abre reservas y empuja la era digital',
    summary: 'GTA VI vuelve al centro del gaming con reservas abiertas, precios altos y debate por el avance del formato digital.',
    content: [
      { type: 'heading', text: 'Lectura XETHKIOZ' },
      { type: 'paragraph', text: 'La noticia no es solo el hype por GTA VI. También muestra hacia dónde se mueve la industria: preventas fuertes, ediciones premium y menos valor real para el formato físico clásico.' },
      { type: 'list', text: 'Reservas abiertas; debate físico/digital; impacto en PS5 y Xbox; precio de entrada más alto' },
    ],
    category: 'gaming',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['gaming', 'gta6', 'radar-externo'],
    source_urls: ['https://www.theguardian.com/games/2026/jun/25/grand-theft-auto-vi-pre-orders-open'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-gaming-xbox-2026-07-01',
    slug: 'radar-gaming-xbox-sube-precios',
    title: 'Radar Gaming · Xbox sube precios y cambia el cálculo consola vs PC',
    summary: 'La suba global de consolas Xbox vuelve a poner sobre la mesa el costo real de jugar en consola.',
    content: [
      { type: 'heading', text: 'Lectura XETHKIOZ' },
      { type: 'paragraph', text: 'Cuando el hardware sube afuera, en LATAM el golpe suele sentirse más fuerte. Esto puede aumentar el interés por PC usada, ofertas y modelos de suscripción.' },
      { type: 'list', text: 'Consolas más caras; presión sobre Game Pass; más debate PC vs consola; impacto posible en Argentina' },
    ],
    category: 'gaming',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['gaming', 'xbox', 'precios'],
    source_urls: ['https://www.reuters.com/business/xbox-raise-console-prices-worldwide-august-2026-06-25/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-ai-un-2026-07-01',
    slug: 'radar-ia-onu-beneficios-riesgos',
    title: 'Radar IA · La ONU pone beneficios y riesgos de IA en la misma mesa',
    summary: 'Un panel científico independiente de Naciones Unidas prepara una evaluación global sobre IA, oportunidades y riesgos.',
    content: [
      { type: 'heading', text: 'Lectura XETHKIOZ' },
      { type: 'paragraph', text: 'La IA ya no es solo una herramienta para crear contenido. Es infraestructura, trabajo, educación, seguridad y política pública.' },
      { type: 'list', text: 'Gobernanza global; evaluación científica; beneficios; riesgos de adopción rápida' },
    ],
    category: 'ai',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['ia', 'onu', 'gobernanza'],
    source_urls: ['https://www.reuters.com/legal/litigation/un-report-sees-enormous-potential-benefits-big-risks-ai-2026-07-01/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-tech-chips-2026-07-01',
    slug: 'radar-tech-chips-ia-micron-qualcomm',
    title: 'Radar Tech · El boom de chips IA también afecta al gamer',
    summary: 'La demanda de IA vuelve a empujar acciones de chips, memoria y centros de datos.',
    content: [
      { type: 'heading', text: 'Lectura XETHKIOZ' },
      { type: 'paragraph', text: 'La IA compite por memoria, almacenamiento y capacidad de fabricación. Eso puede influir en precios y disponibilidad de hardware de consumo.' },
      { type: 'list', text: 'Memoria; SSD; GPUs; centros de datos; precios de componentes' },
    ],
    category: 'tech',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['tech', 'chips', 'ia'],
    source_urls: ['https://www.reuters.com/business/micron-qualcomm-forecasts-ignite-400-billion-ai-chip-stock-rally-2026-06-24/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-meme-sophie-2026-07-01',
    slug: 'meme-radar-sophie-cunningham-dedo-viral',
    title: 'Meme Radar · El gesto silencioso que explotó en redes',
    summary: 'Un clip de Sophie Cunningham señalando en silencio se convirtió en formato de meme por su tensión absurda y fácil de reutilizar.',
    content: [
      { type: 'heading', text: 'Por qué funciona' },
      { type: 'paragraph', text: 'Tiene lectura instantánea: mirada fija, gesto exagerado y una situación fácil de convertir en reacción para discusiones online.' },
      { type: 'quote', text: 'Uso perfecto: cuando alguien insiste en tener razón aunque el build esté fallando.' },
    ],
    category: 'community',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['memes', 'viral', 'internet'],
    source_urls: ['https://people.com/the-best-sophie-cunningham-now-viral-finger-pointing-memes-12008349'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-meme-reset-2026-07-01',
    slug: 'meme-radar-great-meme-reset-2026',
    title: 'Meme Radar · El Great Meme Reset y la nostalgia de internet',
    summary: 'La vuelta irónica a memes viejos y estética 2016 muestra que la nostalgia también puede ser tendencia viral.',
    content: [
      { type: 'heading', text: 'Lectura XETHKIOZ' },
      { type: 'paragraph', text: 'El Great Meme Reset aparece como respuesta al cansancio por formatos caóticos, brainrot y contenido generado en masa.' },
      { type: 'list', text: 'Nostalgia; TikTok; memes clásicos; rechazo al brainrot; cultura digital' },
    ],
    category: 'community',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['memes', 'tiktok', 'nostalgia'],
    source_urls: ['https://www.wired.com/story/the-great-meme-reset-is-coming'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-science-memes-2026-07-01',
    slug: 'science-radar-investigar-viralidad-memes',
    title: 'Science Radar · Investigar memes también es estudiar internet',
    summary: 'La viralidad de memes puede analizarse con señales de contexto, comunidad, imagen y velocidad de propagación.',
    content: [
      { type: 'heading', text: 'Ciencia aplicada a memes' },
      { type: 'paragraph', text: 'La investigación reciente muestra que entender memes requiere contexto actualizado y señales multimodales. No es solo chiste: también es comunicación social.' },
    ],
    category: 'science',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['science', 'memes', 'viralidad'],
    source_urls: ['https://arxiv.org/abs/2606.05316'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
]

export function getCuratedExternalNews(category?: PublicNewsCategory | 'all') {
  if (category && category !== 'all') return curatedExternalNews.filter((article) => article.category === category)
  return curatedExternalNews
}
