import type { PublicNewsArticle, PublicNewsCategory } from './publicNewsService'
import { editorialArticlesAugust2026 } from '../../data/editorialArticles202608'

const PUBLISHED_AT = '2026-07-01T11:30:00.000Z'
const RADAR_UPDATE_AT = '2026-07-02T17:20:00.000Z'
const ARGENTINA_UPDATE_AT = '2026-07-08T17:30:00.000Z'

export const curatedExternalNews: PublicNewsArticle[] = [
  ...editorialArticlesAugust2026,
  {
    id: 'curated-argentina-duendes-2026-07-08',
    slug: 'fun-argentina-mundial-duendes-cuartos',
    title: 'Fun/Mundial · Argentina sigue viva: gracias a los duendes',
    summary: 'Argentina volvió a sobrevivir en modo Mundial y la comunidad XETHKIOZ lo celebra con fe, sufrimiento y un meme original sin escudos ni imágenes oficiales.',
    content: [
      { type: 'heading', text: 'ES · Ganar también es sobrevivir' },
      { type: 'paragraph', text: 'Argentina sigue viva en el Mundial y la lectura emocional es simple: se ganó con sufrimiento, con energía de eliminación directa y con esa mezcla argentina de análisis táctico, cábala y “por favor que termine ya”. Para XETHKIOZ, este tipo de momento entra perfecto en Comunidad/Fun porque no es solamente resultado: es cultura de internet, chat explotado, memes, ansiedad colectiva y celebración compartida.' },
      { type: 'paragraph', text: 'La actualización deja la pieza como radar vivo: primero el festejo por pasar de fase, después la confirmación de que la Selección sigue avanzando en una fase donde cada partido parece una prueba de estrés. La idea no es copiar imágenes oficiales ni usar escudos: la pieza visual es original, con bandera estilizada, duendes propios y estética XETHKIOZ.' },
      { type: 'quote', text: 'Análisis táctico final: fe, sufrimiento y los duendes haciendo QA en el área chica.' },
      { type: 'heading', text: 'EN · Community angle' },
      { type: 'paragraph', text: 'Argentina moving on is more than a scoreline for the community. It becomes a shared internet moment: nerves, memes, lucky rituals, match chat and the feeling that every knockout game is a live server stress test.' },
    ],
    category: 'community',
    status: 'published',
    published_at: ARGENTINA_UPDATE_AT,
    tags: ['argentina', 'mundial', 'duendes', 'meme', 'comunidad'],
    source_urls: ['https://www.reuters.com/sports/soccer/argentina-survive-another-scare-finding-strength-adversity-2026-07-08/', 'https://as.com/futbol/mundial/la-remontada-de-los-dioses-f202607-n/'],
    ai_generated: false,
    created_at: ARGENTINA_UPDATE_AT,
    cover_image_url: '/news/memes/argentina-duendes-cuartos.svg',
  },
  {
    id: 'curated-tech-gourmet-2026-07-02',
    slug: 'radar-tech-negocio-gourmet-ia-automatizacion',
    title: 'Radar Tech · El negocio gourmet entra en la era de IA, datos y automatización',
    summary: 'Restaurantes, marcas gourmet y food service empiezan a depender de POS inteligentes, datos de clientes, automatización y diseño de productos asistido por IA.',
    content: [
      { type: 'heading', text: 'ES · El restaurante ya no es solo cocina' },
      { type: 'paragraph', text: 'El negocio gourmet está cambiando porque la tecnología dejó de estar solo en la caja registradora. Hoy un restaurante competitivo necesita datos de ventas, control de stock, lectura de preferencias, reservas, delivery, fidelización, costos por receta y operación digital. El POS moderno ya no es “un sistema para cobrar”: es el centro operativo que conecta cocina, salón, inventario, reportes y experiencia del cliente.' },
      { type: 'paragraph', text: 'La IA suma otra capa. En producción alimentaria puede ayudar a analizar formulaciones, optimizar procesos, anticipar demanda y diseñar productos con mejor balance entre sabor, nutrición y sustentabilidad. Para un emprendimiento gourmet chico, la lectura práctica es fuerte: quien aprenda a medir costos, clientes y menú con tecnología puede competir mejor, aunque no tenga una estructura gigante.' },
      { type: 'heading', text: 'EN · Why it matters' },
      { type: 'paragraph', text: 'Gourmet businesses are becoming data businesses. POS systems, analytics, inventory tools, AI-assisted product development and digital customer journeys now shape how restaurants survive. The winner is not only the best cook; it is the operator who understands margins, demand, experience and technology at the same time.' },
    ],
    category: 'tech',
    status: 'published',
    published_at: RADAR_UPDATE_AT,
    tags: ['gourmet', 'tech', 'negocios', 'ia'],
    source_urls: ['https://www.techradar.com/news/the-best-pos-system-for-restaurants', 'https://arxiv.org/abs/2511.15728'],
    ai_generated: false,
    created_at: RADAR_UPDATE_AT,
  },
  {
    id: 'curated-ai-food-2026-07-02',
    slug: 'radar-ia-comida-gourmet-recetas-sustentables',
    title: 'Radar IA · Cuando la IA empieza a diseñar comida gourmet',
    summary: 'Nuevos trabajos muestran cómo la IA generativa puede explorar sabor, nutrición y sustentabilidad en recetas y productos alimentarios.',
    content: [
      { type: 'heading', text: 'ES · Del prompt al plato' },
      { type: 'paragraph', text: 'La IA aplicada a comida ya no se limita a recomendar recetas. La investigación reciente apunta a sistemas capaces de aprender patrones de gusto, formular combinaciones nuevas y comparar objetivos que antes chocaban entre sí: que algo sea rico, nutritivo, rentable y más sustentable. Eso abre una puerta enorme para marcas gourmet, cocinas de autor, productos plant-based y emprendimientos que necesitan innovar sin hacer cientos de pruebas a ciegas.' },
      { type: 'paragraph', text: 'La oportunidad no reemplaza al chef: lo vuelve más técnico. Un cocinero, productor o emprendedor puede usar IA como laboratorio conceptual, pero la validación final sigue siendo humana: textura, aroma, cultura local, precio, ingredientes disponibles y experiencia real en mesa. El futuro gourmet probablemente combine creatividad humana con simulación, datos y prueba sensorial.' },
      { type: 'heading', text: 'EN · Human taste plus machine search' },
      { type: 'paragraph', text: 'Generative AI can explore food design spaces faster than traditional trial-and-error. It can suggest combinations optimized for taste, nutrition or sustainability, but the final product still needs chefs, sensory testing and cultural context. Food innovation becomes a hybrid discipline: palate, data and business strategy.' },
    ],
    category: 'ai',
    status: 'published',
    published_at: RADAR_UPDATE_AT,
    tags: ['ia', 'foodtech', 'gourmet', 'sustentabilidad'],
    source_urls: ['https://arxiv.org/abs/2602.03092', 'https://arxiv.org/abs/2509.21556'],
    ai_generated: false,
    created_at: RADAR_UPDATE_AT,
  },
  {
    id: 'curated-gaming-china-asia-2026-07-02',
    slug: 'radar-gaming-china-oriente-juegos-dominan',
    title: 'Asia Gaming · China y Oriente marcan el pulso del gaming actual',
    summary: 'Honor of Kings, Black Myth: Wukong, mobile esports y hardware gamer muestran por qué Asia ya no sigue tendencias: muchas veces las impone.',
    content: [
      { type: 'heading', text: 'ES · Los juegos que explican el mapa' },
      { type: 'paragraph', text: 'China y Oriente están empujando el gaming desde varios frentes a la vez. En mobile, Honor of Kings sigue siendo una referencia central por escala, monetización cosmética, cultura local y ecosistema competitivo. En PC y consola, Black Myth: Wukong demostró que un AAA chino puede vender a escala global usando identidad cultural propia, producción de alto nivel y mitología reconocible.' },
      { type: 'paragraph', text: 'El movimiento no termina en juegos. También aparece en hardware gamer, tablets compactas para esports, pantallas de alta tasa de refresco, optimización por IA y experiencias pensadas para MOBA, FPS y competitivo móvil. Para LATAM, mirar Asia sirve para anticipar lo que después llega a nuestras comunidades: monetización por skins, eventos culturales, mobile competitivo, crossplay y mundos con estética oriental premium.' },
      { type: 'heading', text: 'Top radar XETHKIOZ' },
      { type: 'list', text: 'Honor of Kings; Black Myth: Wukong; Genshin Impact / HoYoverse; PUBG Mobile / Peacekeeper Elite; Delta Force; Mobile Legends en ecosistema Asia; hardware RedMagic orientado a esports' },
      { type: 'heading', text: 'EN · Asia is not a secondary market' },
      { type: 'paragraph', text: 'Asian gaming is shaping global behavior across mobile esports, premium PC releases, cultural IP and performance-focused hardware. For creators and players in LATAM, tracking China, Korea, Japan and Southeast Asia is a way to see tomorrow’s trends before they become mainstream locally.' },
    ],
    category: 'gaming',
    status: 'published',
    published_at: RADAR_UPDATE_AT,
    tags: ['asia-gaming', 'china', 'mobile', 'esports'],
    source_urls: ['https://www.businessinsider.com/tencent-game-honor-of-kings-what-china-gaming-gets-right-2025-3', 'https://www.ft.com/content/24d330fe-6f82-4571-85ec-8e1d429d6da1', 'https://www.androidcentral.com/tablets/redmagics-compact-esports-ready-gaming-tablet-is-here-and-global-users-should-prepare'],
    ai_generated: false,
    created_at: RADAR_UPDATE_AT,
  },
  {
    id: 'curated-meme-gourmet-ai-2026-07-02',
    slug: 'meme-fun-cocina-gourmet-ia-wifi-inestable',
    title: 'Fun/Meme · Cocina gourmet, IA y Wi‑Fi inestable',
    summary: 'Meme original de XETHKIOZ sobre el choque entre cocina de autor, automatización y la realidad de cualquier negocio chico: todo depende del Wi‑Fi.',
    content: [
      { type: 'heading', text: 'ES · El meme' },
      { type: 'paragraph', text: 'Cuando el restaurante dice “cocina de autor”, pero el menú lo optimizó una IA con hambre y Wi‑Fi inestable. Es una broma simple, pero toca algo real: cada negocio moderno quiere sonar futurista, aunque a veces la operación diaria depende de que no se caiga internet, que el POS responda y que el sistema de pedidos no decida actualizar justo en hora pico.' },
      { type: 'paragraph', text: 'Este meme queda dentro de Fun/Meme porque conecta dos mundos de la web: tecnología y negocio gourmet. La idea es que la sección tenga humor propio, visual original y lectura cultural, sin depender de copiar memes externos.' },
      { type: 'quote', text: 'Chef IA v2.6 recomienda: reiniciar el router antes del servicio.' },
      { type: 'heading', text: 'EN · Meme reading' },
      { type: 'paragraph', text: 'The joke works because every “AI-powered” business still depends on basic infrastructure. Gourmet branding, automation and unstable Wi‑Fi create the perfect small-business meme.' },
    ],
    category: 'community',
    status: 'published',
    published_at: RADAR_UPDATE_AT,
    tags: ['meme', 'fun', 'gourmet', 'ia'],
    source_urls: [],
    ai_generated: false,
    created_at: RADAR_UPDATE_AT,
    cover_image_url: '/news/memes/gourmet-ai-meme.svg',
  },
  {
    id: 'curated-gaming-gta-vi-2026-07-01',
    slug: 'radar-gaming-gta-vi-reservas-digital',
    title: 'Radar Gaming · GTA VI abre reservas y empuja la era digital',
    summary: 'GTA VI vuelve al centro del gaming con reservas abiertas, precios altos y debate por el avance del formato digital.',
    content: [
      { type: 'heading', text: 'ES · Qué está pasando' },
      { type: 'paragraph', text: 'GTA VI vuelve a dominar la conversación porque sus reservas ya funcionan como evento global, no como una simple preventa. El punto fuerte no es solamente que el juego genere expectativa: también deja ver cómo la industria empuja cada vez más al jugador hacia ediciones digitales, acceso anticipado, paquetes premium y compras antes de tener reviews completas. Para la comunidad, esto cambia la forma de decidir: ya no alcanza con mirar el tráiler, también hay que mirar precio, plataforma, edición, beneficios reales y qué tan físico es realmente el producto que se compra.' },
      { type: 'paragraph', text: 'La lectura gamer para LATAM es clara: un lanzamiento de este tamaño marca referencia de precios para todo lo que viene después. Si GTA VI instala una barrera de entrada más alta, otros publishers pueden tomarlo como permiso para subir valores. En Argentina, además, cualquier diferencia internacional se amplifica con impuestos, dólar, stores regionales y reventa. Por eso esta noticia importa incluso para quien no piensa comprarlo el primer día.' },
      { type: 'heading', text: 'EN · Why it matters' },
      { type: 'paragraph', text: 'GTA VI is not just a game launch; it is a market signal. Pre-orders, premium editions and digital-first distribution show where big releases are moving. Players need to compare real value, platform conditions and edition details before jumping into the hype. For LATAM, the impact is stronger because global price changes usually become heavier once exchange rates, taxes and store policies are added.' },
    ],
    category: 'gaming',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['gaming', 'gta6', 'radar-externo'],
    source_urls: ['https://www.theguardian.com/games/2026/jun/25/grand-theft-auto-vi-pre-orders-open'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-gaming-xbox-2026-07-01',
    slug: 'radar-gaming-xbox-sube-precios',
    title: 'Radar Gaming · Xbox sube precios y cambia el cálculo consola vs PC',
    summary: 'La suba global de consolas Xbox vuelve a poner sobre la mesa el costo real de jugar en consola.',
    content: [
      { type: 'heading', text: 'ES · El dato importante' },
      { type: 'paragraph', text: 'Xbox prepara una suba global de consolas en un contexto donde memoria y almacenamiento se volvieron más caros por la presión de toda la industria tecnológica. Esto no golpea solo a Microsoft: afecta a cualquier dispositivo que dependa de chips, SSD, RAM y cadenas de suministro tensas. En gaming, el impacto se nota más porque las consolas suelen venderse con márgenes ajustados y dependen de volumen, servicios y juegos para recuperar valor.' },
      { type: 'paragraph', text: 'Para un jugador argentino o latinoamericano, la pregunta real es práctica: ¿conviene seguir en consola, esperar una oferta, buscar usado, pasar a PC o apoyarse más en servicios? Una suba así también cambia el valor percibido de Game Pass, de los bundles y de las generaciones actuales. Si la consola sube, el mercado usado y los planes de financiación pueden volverse más relevantes que el lanzamiento nuevo.' },
      { type: 'heading', text: 'EN · Market reading' },
      { type: 'paragraph', text: 'The Xbox price increase shows how AI-driven component demand can reach regular players. Storage and memory costs do not stay inside datacenters; they can affect consoles, laptops, handhelds and creator hardware. For gamers, this makes the console-versus-PC decision less emotional and more economic: total cost, services, used hardware and long-term access become part of the same calculation.' },
    ],
    category: 'gaming',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['gaming', 'xbox', 'precios'],
    source_urls: ['https://www.reuters.com/business/xbox-raise-console-prices-worldwide-august-2026-06-25/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-ai-un-2026-07-01',
    slug: 'radar-ia-onu-beneficios-riesgos',
    title: 'Radar IA · La ONU pone beneficios y riesgos de IA en la misma mesa',
    summary: 'Un panel científico independiente de Naciones Unidas prepara una evaluación global sobre IA, oportunidades y riesgos.',
    content: [
      { type: 'heading', text: 'ES · Por qué no es una nota más de IA' },
      { type: 'paragraph', text: 'La ONU vuelve a poner el tema IA en una escala que supera a las apps de moda. El panel científico independiente busca ordenar beneficios, riesgos y gobernanza en un momento donde los modelos avanzan más rápido que las leyes, la educación y la capacidad técnica de muchos países. Eso importa porque la IA ya no es solo una herramienta para crear textos o imágenes: está entrando en trabajo, salud, educación, fraude, seguridad, ciencia y administración pública.' },
      { type: 'paragraph', text: 'Para XETHKIOZ, la lectura es doble. Por un lado, la IA puede ayudar a creadores, estudiantes, periodistas independientes y pequeños proyectos a producir mejor. Por otro, si se usa sin criterio puede amplificar desinformación, sesgos, automatización irresponsable y dependencia de proveedores externos. La clave no es estar a favor o en contra: es entender qué se puede verificar, qué se debe revisar y qué nunca conviene publicar sin control humano.' },
      { type: 'heading', text: 'EN · The useful angle' },
      { type: 'paragraph', text: 'The UN discussion matters because AI is becoming infrastructure. It can improve productivity and access to knowledge, but it also raises risks around safety, misinformation, jobs and unequal access. The practical takeaway is simple: creators should use AI as support, not as an autopilot. Verification, transparency and human review remain essential.' },
    ],
    category: 'ai',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['ia', 'onu', 'gobernanza'],
    source_urls: ['https://www.reuters.com/legal/litigation/un-report-sees-enormous-potential-benefits-big-risks-ai-2026-07-01/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-tech-chips-2026-07-01',
    slug: 'radar-tech-chips-ia-micron-qualcomm',
    title: 'Radar Tech · El boom de chips IA también afecta al gamer',
    summary: 'La demanda de IA vuelve a empujar acciones de chips, memoria y centros de datos.',
    content: [
      { type: 'heading', text: 'ES · Tecnología que llega al bolsillo' },
      { type: 'paragraph', text: 'El rally de empresas vinculadas a chips de IA no es solo una noticia financiera. Detrás hay una tensión concreta: los centros de datos necesitan GPU, memoria, almacenamiento, energía y redes. Cuando esa demanda crece, puede competir con el hardware que usan gamers, streamers y creadores. Por eso una noticia sobre Micron o Qualcomm puede terminar afectando el precio de una notebook, un SSD, una placa de video o una consola.' },
      { type: 'paragraph', text: 'El punto importante es que la IA no vive únicamente en “la nube”. Necesita infraestructura física, y esa infraestructura usa los mismos tipos de componentes que también necesita el mercado de consumo. Para quien arma PC o mejora setup, conviene mirar estas tendencias antes de comprar: memoria, almacenamiento y GPU pueden subir, cambiar disponibilidad o empujar a elegir generaciones anteriores con mejor relación precio/rendimiento.' },
      { type: 'heading', text: 'EN · Why gamers should care' },
      { type: 'paragraph', text: 'AI hardware demand can influence consumer hardware. Datacenters compete for memory, storage and advanced chips, and that pressure may reach gaming PCs, laptops and consoles. For players and creators, the smart move is to watch component trends before upgrading and avoid buying only because of hype.' },
    ],
    category: 'tech',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['tech', 'chips', 'ia'],
    source_urls: ['https://www.reuters.com/business/micron-qualcomm-forecasts-ignite-400-billion-ai-chip-stock-rally-2026-06-24/'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-meme-sophie-2026-07-01',
    slug: 'meme-radar-sophie-cunningham-dedo-viral',
    title: 'Meme Radar · El gesto silencioso que explotó en redes',
    summary: 'Un clip de Sophie Cunningham señalando en silencio se convirtió en formato de meme por su tensión absurda y fácil de reutilizar.',
    content: [
      { type: 'heading', text: 'ES · Por qué se volvió meme' },
      { type: 'paragraph', text: 'El gesto de Sophie Cunningham funciona como meme porque se entiende sin explicación: una mirada fija, un dedo señalando y una tensión que cualquiera puede traducir a discusiones de internet. Ese tipo de formato es ideal para redes porque no depende de conocer todo el contexto deportivo; alcanza con reconocer la emoción. El usuario lo puede usar para decir “te lo dije”, “mirá esto” o “ahí está el culpable” sin escribir demasiado.' },
      { type: 'paragraph', text: 'En la sección Memes de XETHKIOZ, este tipo de contenido sirve como radar cultural. No se trata de copiar el clip ni robar una imagen viral: se trata de explicar por qué un gesto se transforma en lenguaje compartido. Los memes más fuertes suelen tener tres elementos: expresión clara, situación adaptable y timing. Cuando coinciden, la comunidad hace el resto.' },
      { type: 'heading', text: 'EN · Meme logic' },
      { type: 'paragraph', text: 'The meme works because the gesture is readable instantly. It can be reused in sports, gaming, work chats or creator jokes without needing the original context. Strong memes usually combine a clear emotion, a flexible template and perfect timing. That is why a small moment can travel far beyond the event where it started.' },
    ],
    category: 'community',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['memes', 'viral', 'internet'],
    source_urls: ['https://people.com/the-best-sophie-cunningham-now-viral-finger-pointing-memes-12008349'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-meme-reset-2026-07-01',
    slug: 'meme-radar-great-meme-reset-2026',
    title: 'Meme Radar · El Great Meme Reset y la nostalgia de internet',
    summary: 'La vuelta irónica a memes viejos y estética 2016 muestra que la nostalgia también puede ser tendencia viral.',
    content: [
      { type: 'heading', text: 'ES · Internet mira hacia atrás' },
      { type: 'paragraph', text: 'El Great Meme Reset aparece como una respuesta al cansancio de parte de la comunidad frente a memes caóticos, contenido generado en masa y formatos que muchos sienten demasiado vacíos. La propuesta de volver a memes más reconocibles no es solo nostalgia: también es una búsqueda de internet más humana, con chistes que tengan contexto, historia o al menos una estructura fácil de entender.' },
      { type: 'paragraph', text: 'Para XETHKIOZ, esto es útil porque muestra cómo la cultura digital se recicla. Lo que hoy parece viejo puede volver con otra lectura, otra generación y otro formato. La pregunta no es si el reset va a funcionar literalmente, sino por qué tantos usuarios sienten que los memes actuales perdieron identidad. Esa tensión entre nostalgia, IA, TikTok y humor rápido explica gran parte de la conversación viral de 2026.' },
      { type: 'heading', text: 'EN · Cultural reading' },
      { type: 'paragraph', text: 'The Great Meme Reset is less about literally resetting the internet and more about a reaction against low-effort, AI-looking and overly chaotic meme culture. Nostalgia becomes a tool to ask for clearer, more human and more recognizable humor. Even if the movement fails, the conversation shows that meme culture is changing again.' },
    ],
    category: 'community',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['memes', 'tiktok', 'nostalgia'],
    source_urls: ['https://www.wired.com/story/the-great-meme-reset-is-coming'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
  {
    id: 'curated-science-memes-2026-07-01',
    slug: 'science-radar-investigar-viralidad-memes',
    title: 'Science Radar · Investigar memes también es estudiar internet',
    summary: 'La viralidad de memes puede analizarse con señales de contexto, comunidad, imagen y velocidad de propagación.',
    content: [
      { type: 'heading', text: 'ES · Ciencia aplicada a cultura digital' },
      { type: 'paragraph', text: 'Estudiar memes puede sonar liviano, pero en realidad ayuda a entender cómo se mueve la información en internet. Un meme combina imagen, texto, contexto, comunidad, repetición y velocidad. Cuando investigadores analizan estos patrones, pueden detectar cómo nace una tendencia, por qué algunas piezas viajan más rápido y cómo ciertos formatos se transforman al pasar de una plataforma a otra.' },
      { type: 'paragraph', text: 'Esto también sirve para una web de gaming y tecnología. Si entendemos por qué se viraliza un meme, podemos leer mejor la cultura de la comunidad: qué le causa gracia, qué rechaza, qué repite y qué convierte en identidad. En XETHKIOZ, la sección Memes no tiene que ser solo descanso visual; puede ser una forma de observar internet sin perder el humor.' },
      { type: 'heading', text: 'EN · Why research matters' },
      { type: 'paragraph', text: 'Memes are not just jokes. They are fast cultural signals that reveal how communities react, remix and share meaning. Studying them helps explain online behavior, platform dynamics and the way visual language spreads. For a gaming and tech community, meme analysis can show what people actually care about before it becomes formal news.' },
    ],
    category: 'science',
    status: 'published',
    published_at: PUBLISHED_AT,
    tags: ['science', 'memes', 'viralidad'],
    source_urls: ['https://arxiv.org/abs/2606.05316'],
    ai_generated: false,
    created_at: PUBLISHED_AT,
  },
]

export function getCuratedExternalNews(category?: PublicNewsCategory | 'all') {
  if (category && category !== 'all') return curatedExternalNews.filter((article) => article.category === category)
  return curatedExternalNews
}
