export { default as CmsDashboard } from './CmsDashboard'
export { default as CmsGenerate } from './CmsGenerate'
export { default as CmsNewsEditor } from './CmsNewsEditor'
export { default as CmsNewsList } from './CmsNewsList'
export { default as CmsWebQuotes } from './CmsWebQuotes'
export { default as CmsWebServicesManager } from './CmsWebServicesManager'
