import { Link } from 'react-router-dom'
import SEO from '../components/SEO'

export default function About() {
  return <main className="xk-about-universe mx-auto max-w-6xl px-4 py-12 text-white sm:px-6">
    <SEO title="El universo XETHKIOZ" description="La historia, identidad y misión detrás de XETHKIOZ: gaming, tecnología y cultura digital desde Argentina." url="/about" />
    <section className="xk-about-hero"><p>ORIGIN FILE // ARGENTINA</p><h1>No quería hacer otra página. Quería construir un universo.</h1><span>XETHKIOZ nace de una vida atravesada por los videojuegos, el trabajo, la tecnología y la necesidad de crear algo propio. Un lugar donde cada sección se sienta distinta, pero todas formen parte de la misma ciudad digital.</span></section>
    <section className="xk-about-story"><div><p>CREATOR // ALEXIS DÍAZ</p><h2>La mirada de un gamer adulto</h2></div><div><p>No escribo desde una oficina corporativa ni desde un personaje inventado. Trabajo en salud, soy padre, juego cuando el tiempo lo permite y sigo sintiendo la misma curiosidad por los mundos virtuales, las nuevas tecnologías y las historias extrañas.</p><p>Por eso XETHKIOZ no busca competir por publicar primero a cualquier precio. Busca explicar mejor, separar el dato del rumor y convertir cada visita en una experiencia con identidad.</p></div></section>
    <section className="xk-about-districts"><article><small>01 // 遊戯区</small><h2>Gaming</h2><p>Noticias, misiones, builds, comunidad y señales de Asia vistas desde la experiencia real de quien juega.</p></article><article><small>02 // 未来区</small><h2>Ciencia y tecnología</h2><p>Herramientas, IA y descubrimientos explicados con fuentes, contexto y utilidad práctica.</p></article><article><small>03 // 笑街</small><h2>FUN</h2><p>Memes, clips y caos compartible. El sector que recuerda que internet también existe para reírse.</p></article><article><small>13 // 禁制区</small><h2>Green Node</h2><p>Privacidad, hacking defensivo, documentos y misterios analizados sin vender ficción como evidencia.</p></article></section>
    <section className="xk-about-manifesto"><p>MANIFIESTO</p><h2>Gaming Is My Passion.<br />Beyond The Game.</h2><span>El objetivo es que XETHKIOZ crezca como medio, comunidad, estudio creativo y universo narrativo independiente. Con luces, portales y energía; también con responsabilidad, humanidad y una voz reconocible.</span><div><Link to="/news">Explorar dossiers →</Link><Link to="/community">Entrar a la comunidad →</Link><Link to="/support">Apoyar el universo →</Link></div></section>
  </main>
}
