-- XETHKIOZ editorial library: 30 sourced Gaming dossiers.
-- Idempotent: every dossier is keyed by a stable editorial slug.

with editorial (
  slug, title, summary, source_url, signal, context, xeth_read, tags, cover_image_url, cover_image_alt
) as (
  values
  ('gaming-poe-curse-of-allflame-twitch-drops', 'Curse of Allflame activa sus Twitch Drops', 'Grinding Gear Games confirmó recompensas cosméticas por mirar las transmisiones habilitadas de la nueva expansión de Path of Exile.', 'https://www.pathofexile.com/forum/view-thread/3985053', 'La campaña oficial detalla la ventana de Drops, los canales elegibles y el vínculo necesario entre las cuentas de Twitch y Path of Exile.', 'Los Drops no modifican el poder del personaje: son recompensas visuales pensadas para acompañar el lanzamiento y concentrar a la comunidad alrededor de los directos.', 'Antes de dejar una pestaña abierta, conviene revisar que ambas cuentas estén enlazadas y que el progreso aparezca en el inventario de Twitch. Señal oficial, ritual opcional.', array['path-of-exile','twitch','drops'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero del Nexus Gaming frente a un portal violeta'),
  ('gaming-poe-329-reliquarian-ascendancy', 'Path of Exile 3.29 reajusta la ascendencia Reliquarian', 'GGG publicó los cambios de Reliquarian antes de 3.29 para que la comunidad pueda rehacer sus planes de build con información oficial.', 'https://www.pathofexile.com/forum/view-thread/3984866', 'El anuncio enumera cambios concretos de la ascendencia y funciona como referencia primaria previa al parche.', 'Una variación de ascendencia puede alterar rutas de pasivas, objetos prioritarios y economía temprana. La lectura correcta exige comparar el texto final con la versión jugable.', 'No copies una build vieja como si fuera un grimorio eterno: guardá la versión, revisá números y probá el árbol en un entorno recuperable.', array['path-of-exile','builds','3.29'], '/assets/portal-games-clean-v1.webp', 'Portal violeta de videojuegos con ciudad futurista'),
  ('gaming-poe-mirage-league-end', 'Qué pasa cuando termina Mirage League', 'Grinding Gear Games explicó el destino de personajes, objetos y progreso cuando cierre Mirage League.', 'https://www.pathofexile.com/forum/view-thread/3984581', 'La comunicación oficial aclara la transición de la liga y evita depender de rumores sobre migraciones o pérdida de inventario.', 'Los cierres de temporada afectan almacenamiento, comercio y planes de último minuto. Leer la letra oficial permite ordenar pestañas y decidir qué conservar.', 'El verdadero jefe final de cada liga no siempre es un mapa: a veces es el inventario. Prepará la migración sin pánico y con espacio libre.', array['path-of-exile','mirage-league','temporada'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero anime dentro del portal gamer de Xethkioz'),
  ('gaming-poe-allflame-they-rise-again', 'Curse of Allflame: ellos vuelven a levantarse', 'El avance oficial de Path of Exile presenta el tono, las amenazas y la identidad de la expansión Curse of Allflame.', 'https://www.pathofexile.com/forum/view-thread/3984299', 'GGG publicó una pieza centrada en el regreso de enemigos y en la atmósfera de la nueva etapa.', 'Un tráiler establece intención y fantasía, pero no reemplaza notas de parche ni datos de balance. Sirve para entender el mundo antes de calcular daño.', 'Esta es la clase de señal que entra perfecta al Nexus: oscuridad, fuego y builds todavía por descifrar, separando hype de mecánicas confirmadas.', array['path-of-exile','curse-of-allflame','expansion'], '/assets/portal-games-clean-v1.webp', 'Energía violeta rodeando un portal de videojuegos'),
  ('gaming-poe-new-transfigured-skills', 'Nuevas gemas transfiguradas cambian el laboratorio de builds', 'Path of Exile reveló nuevas habilidades transfiguradas y abrió otra ronda de experimentación para la temporada 3.29.', 'https://www.pathofexile.com/forum/view-thread/3982460', 'La publicación oficial muestra variantes de habilidades existentes con comportamientos distintos.', 'Estas gemas no son simples mejoras lineales: pueden cambiar la forma de escalar, posicionarse o combinar soportes. El valor real aparece al probar interacciones.', 'Guardá capturas de la descripción y anotá la versión del parche. En el Nexus, una build sin contexto temporal es una reliquia peligrosa.', array['path-of-exile','skills','buildcraft'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Arte de identidad del Nexus Gaming'),
  ('gaming-poe-allflame-july-24', 'Curse of Allflame abre el portal el 24 de julio', 'GGG fijó la fecha de lanzamiento de la expansión y concentró en su anuncio la referencia oficial para el comienzo de liga.', 'https://www.pathofexile.com/forum/view-thread/3982050', 'El estudio confirmó el 24 de julio como fecha de salida y enlazó la presentación de contenidos de la expansión.', 'Una fecha oficial ordena vacaciones, party, descarga y preparación de filtros. La hora regional y cualquier mantenimiento deben verificarse cerca del estreno.', 'Marcá el calendario, pero no sacrifiques el sueño al altar del queue. La primera misión es llegar con cliente actualizado y expectativas reales.', array['path-of-exile','launch','3.29'], '/assets/portal-games-clean-v1.webp', 'Portal gamer violeta abierto sobre una ciudad de neón'),
  ('gaming-poe-return-of-the-ancestors', 'Return of the Ancestors recupera una batalla conocida', 'Path of Exile anunció un evento temporal que vuelve sobre el sistema de Ancestors con reglas y recompensas propias.', 'https://www.pathofexile.com/forum/view-thread/3968867', 'La página oficial concentra duración, condiciones y recompensas del evento.', 'Los eventos de regreso permiten comparar cómo envejeció una mecánica y probar personajes fuera del ritmo normal de liga. También requieren revisar qué progreso migra.', 'Entrá por nostalgia, quedate por el experimento. La memoria del jugador es fuerte; las reglas vigentes son más fuertes.', array['path-of-exile','event','ancestors'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero del Nexus bajo un cielo violeta'),
  ('gaming-poe-329-timeline', 'La hoja de ruta de Path of Exile 3.29', 'Grinding Gear Games compartió el calendario preliminar de la próxima expansión y dio una ventana clara para la comunidad.', 'https://www.pathofexile.com/forum/view-thread/3955013', 'La cronología oficial organiza anuncios, revelación y lanzamiento alrededor de la versión 3.29.', 'Una hoja de ruta es una promesa operativa, no una garantía inmutable. Conviene seguir las actualizaciones del mismo foro si el desarrollo obliga a ajustar fechas.', 'El radar Xethkioz toma el timeline como mapa, no como profecía: cada hito se verifica cuando la señal oficial vuelve a encenderse.', array['path-of-exile','roadmap','3.29'], '/assets/portal-games-clean-v1.webp', 'Arco de energía violeta del portal de Gaming'),
  ('gaming-poe-server-performance-3280c', 'GGG detalla el rendimiento de servidores después de 3.28.0c', 'El estudio informó qué observó tras el parche de servidor y cómo continuaría investigando los problemas de rendimiento.', 'https://www.pathofexile.com/forum/view-thread/3921957', 'La actualización viene del operador del servicio y describe el estado posterior a 3.28.0c.', 'Latencia, pérdida de paquetes y carga del reino pueden sentirse igual para el jugador, aunque tengan causas diferentes. Un informe oficial ayuda a no culpar al equipo local sin medir.', 'Antes de exorcizar el router: registrá región, horario, instancia y trazas. El lag también deja evidencia.', array['path-of-exile','servers','performance'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Señal violeta del universo Gaming de Xethkioz'),
  ('gaming-poe-server-instability', 'Path of Exile reconoce inestabilidad reciente del servidor', 'GGG publicó una comunicación específica sobre caídas e inestabilidad para mantener informada a la comunidad.', 'https://www.pathofexile.com/forum/view-thread/3919345', 'El mensaje confirma que el problema fue observado por el equipo y evita tratar reportes aislados como una causa ya demostrada.', 'Reconocer una incidencia es distinto de cerrar su diagnóstico. La recuperación puede ser gradual y algunas instancias conservar síntomas durante el análisis.', 'Si el reino tiembla, no arriesgues una misión crítica. Capturá el error, evitá duplicar rumores y seguí el hilo oficial.', array['path-of-exile','servers','incident'], '/assets/portal-games-clean-v1.webp', 'Portal púrpura de Gaming con electricidad'),
  ('gaming-riot-parental-controls', 'Riot amplía sus controles parentales', 'Riot Games presentó nuevas herramientas para que las familias administren aspectos de la experiencia de juego.', 'https://www.riotgames.com/en/news/parental-control-features', 'La compañía describe funciones parentales y el alcance de su despliegue dentro de sus productos.', 'Los controles ayudan a establecer límites, pero no sustituyen conversaciones sobre tiempo, compras, privacidad y trato con desconocidos.', 'Una cuenta segura también es parte del build: correo protegido, 2FA cuando esté disponible y reglas familiares que todos entiendan.', array['riot-games','seguridad','familias'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Identidad anime gamer de Xethkioz'),
  ('gaming-riot-classic-mayhem-update', 'Riot adelanta Classic, Mayhem y sus próximas pruebas', 'Una actualización de desarrollo reúne el estado de nuevos modos y los próximos pasos del ecosistema de League of Legends.', 'https://www.riotgames.com/en/news/dev-update-classic-mayhem-more', 'Riot centralizó en un video y artículo oficial el avance de Classic, Mayhem y otros cambios.', 'Los dev updates sirven para entender intención y prioridades, pero cada modo puede cambiar antes de llegar al cliente final.', 'Tomalo como transmisión desde el laboratorio, no como notas de parche talladas en piedra. La versión live manda.', array['riot-games','league-of-legends','dev-update'], '/assets/portal-games-clean-v1.webp', 'Nexo gamer violeta con paisaje futurista'),
  ('gaming-league-classic-date', 'League Classic ya tiene fecha de apertura', 'Riot comunicó cuándo estará disponible League Classic y cómo se integra al calendario del juego.', 'https://www.riotgames.com/en/news/league-classic-live-date', 'La fecha proviene del canal corporativo oficial de Riot Games.', 'Recuperar una experiencia clásica no significa reconstruir cada detalle de memoria. Compatibilidad moderna, seguridad y comunidad condicionan la implementación.', 'La nostalgia entra al portal con parche nuevo. Compará sensaciones, pero también documentá qué cambió de verdad.', array['league-of-legends','classic','riot-games'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero anime vigilando el Nexus'),
  ('gaming-tft-enchanted-wilds', 'TFT revela Enchanted Wilds', 'Teamfight Tactics presentó el concepto de Enchanted Wilds y las ideas de diseño que sostienen el nuevo set.', 'https://www.riotgames.com/en/news/tft-dev-drop-enchanted-wilds-i-dev-video-teamfight-tactics', 'El Dev Drop oficial funciona como introducción del equipo a la temática y sus sistemas.', 'Un set nuevo reinicia el lenguaje del metajuego: rasgos, economía y posicionamiento deben aprenderse otra vez. Las primeras tier lists son hipótesis aceleradas.', 'Entrá al bosque encantado con libreta. La composición más ruidosa del día uno no siempre sobrevive a la primera semana.', array['tft','enchanted-wilds','autobattler'], '/assets/portal-games-clean-v1.webp', 'Portal de videojuegos iluminado por energía violeta'),
  ('gaming-riftbound-vendetta', 'Riftbound inicia su Vendetta', 'Riot presentó Vendetta como una nueva etapa para su juego de cartas físico ambientado en League of Legends.', 'https://www.riotgames.com/en/news/the-vendetta-begins', 'La noticia oficial introduce la colección y su lugar dentro de Riftbound.', 'Cada expansión modifica el entorno competitivo y también el mercado de cartas. Conviene separar valor de juego, rareza y especulación de reventa.', 'Abrí sobres por diversión, no como plan financiero. El Nexus registra mazos; no promete tesoros.', array['riftbound','vendetta','card-game'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Héroe anime dentro del mundo Gaming'),
  ('gaming-convergence-fest', 'Convergence Fest cruza TFT y Riftbound', 'Riot anunció un evento combinado para acercar a las comunidades de Teamfight Tactics y Riftbound.', 'https://www.riotgames.com/en/news/introducing-convergence-fest-tft-riftbound-combined', 'El anuncio oficial explica la convergencia de ambas experiencias en un mismo encuentro.', 'Los eventos híbridos prueban cuánto puede viajar una comunidad entre pantalla y mesa. También son una oportunidad para enseñar reglas a jugadores nuevos.', 'Dos portales, una misma party: llegá con curiosidad y sin asumir que dominar TFT equivale a dominar un mazo físico.', array['tft','riftbound','community-event'], '/assets/portal-games-clean-v1.webp', 'Arco del portal gamer de Xethkioz'),
  ('gaming-league-200-years', 'Riot revisita sus “200 años” de experiencia', 'League of Legends recupera uno de sus memes históricos para explicar decisiones, errores y aprendizaje de diseño.', 'https://www.riotgames.com/en/news/200-years-of-experience-league-of-legends', 'La propia Riot vuelve sobre la frase que la comunidad convirtió en meme.', 'Cuando un estudio adopta un meme crítico puede abrir una conversación útil, siempre que el análisis no se quede sólo en autoparodia.', 'El humor baja la defensa; los datos de balance completan la historia. Reírse del pasado sirve si mejora el próximo parche.', array['league-of-legends','meme','game-design'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Energía anime alrededor del Nexus Gamer'),
  ('gaming-switch-2-system', 'Nintendo Switch 2 redefine la consola híbrida', 'Nintendo detalla su nueva plataforma, la compatibilidad prevista y las funciones que amplían la idea original de Switch.', 'https://www.nintendo.com/us/gaming-systems/switch-2/', 'La ficha oficial reúne disponibilidad, precio sugerido y características principales del sistema.', 'Una compra responsable exige mirar catálogo, compatibilidad real, almacenamiento y costo de accesorios, no sólo potencia o entusiasmo de lanzamiento.', 'El portal nuevo brilla, pero el inventario importa: revisá qué juegos y controles ya tenés antes de pagar el salto generacional.', array['nintendo','switch-2','hardware'], '/assets/portal-games-clean-v1.webp', 'Portal gamer futurista en color violeta'),
  ('gaming-switch-2-gamechat', 'GameChat lleva voz y video al centro de Switch 2', 'Nintendo presenta GameChat como una forma integrada de conversar y compartir sesiones con otros jugadores.', 'https://www.nintendo.com/us/gaming-systems/switch-2/', 'La página oficial describe GameChat y los requisitos asociados a su uso.', 'La comunicación integrada reduce fricción, pero amplía la superficie de privacidad. Cámara, micrófono, contactos y menores requieren configuración consciente.', 'Antes de invocar a toda la party, revisá permisos. Un buen chat empieza con gente conocida y termina cuando vos decidís.', array['nintendo','gamechat','privacy'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Nexus violeta con personaje gamer'),
  ('gaming-switch-2-gameshare', 'GameShare propone compartir una partida cercana', 'Nintendo explica cómo ciertos juegos compatibles pueden compartirse para jugar con otras consolas del entorno.', 'https://www.nintendo.com/us/gaming-systems/switch-2/', 'GameShare figura entre las funciones oficiales de Switch 2, con disponibilidad sujeta a títulos compatibles.', 'La palabra compartir no significa propiedad permanente ni compatibilidad universal. Cada juego define el alcance y los participantes necesitan equipos admitidos.', 'Es una puerta para sumar gente a la partida, no un hechizo de biblioteca infinita. Mirá la ficha del juego antes de organizar la noche.', array['nintendo','gameshare','multiplayer'], '/assets/portal-games-clean-v1.webp', 'Universo gamer abierto por un portal violeta'),
  ('gaming-switch-2-compatibility', 'La retrocompatibilidad de Switch 2 necesita lectura fina', 'Nintendo informa que la nueva consola puede ejecutar juegos compatibles de Switch, aunque existen excepciones y diferencias.', 'https://www.nintendo.com/us/gaming-systems/switch-2/', 'La compatibilidad se comunica oficialmente con el matiz de que no todo el catálogo funciona de la misma manera.', 'Retrocompatibilidad no es una respuesta binaria: controles, periféricos, actualizaciones y funciones específicas pueden condicionar cada título.', 'No vendas la consola vieja por una frase del tráiler. Consultá tu biblioteca juego por juego y guardá la lista como si fuera una build.', array['nintendo','compatibility','switch-2'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Portal Gaming con electricidad púrpura'),
  ('gaming-switch-2-display-performance', 'Pantalla y rendimiento: qué promete Switch 2', 'Nintendo reúne especificaciones de imagen y rendimiento para explicar el salto técnico de su nueva consola.', 'https://www.nintendo.com/us/gaming-systems/switch-2/', 'La información oficial describe capacidades máximas del hardware, sujetas al juego, modo y pantalla utilizados.', 'Una cifra máxima no garantiza que todos los títulos la alcancen. Resolución, cuadros por segundo, batería y temperatura se equilibran de forma diferente.', 'Leé “hasta” como una condición técnica, no como aura mágica. La experiencia final se prueba juego por juego.', array['nintendo','display','performance'], '/assets/portal-games-clean-v1.webp', 'Portal violeta de nueva generación gamer'),
  ('gaming-xbox-gears-eday-pc', 'Gears of War: E-Day prepara su despliegue en PC', 'Xbox Wire publicó detalles sobre la versión para PC y el trabajo técnico alrededor del regreso de Gears.', 'https://news.xbox.com/en-us/', 'El portal oficial de Xbox reúne la comunicación del proyecto y sus novedades de plataforma.', 'Una versión de PC se evalúa por escalabilidad, controles, accesibilidad y estabilidad, no sólo por capturas de máxima calidad.', 'La motosierra puede esperar: primero revisá requisitos, drivers y opciones. Un lanzamiento épico también necesita frametime estable.', array['xbox','gears-of-war','pc'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero gamer rodeado de energía violeta'),
  ('gaming-xbox-modern-warfare-4', 'Modern Warfare 4 entra en el radar de Xbox', 'Xbox Wire incorporó la nueva entrega de Call of Duty a su cobertura oficial de próximos lanzamientos.', 'https://news.xbox.com/en-us/', 'La señal proviene del medio editorial oficial de Xbox y debe complementarse con la ficha final del juego.', 'En una saga anual, modos, monetización y requisitos pueden cambiar mucho entre anuncio y salida. Reservar exige esperar detalles concretos.', 'El nombre abre el portal; el contenido decide si entramos. Nada de declarar victoria antes de ver campaña, multijugador y rendimiento.', array['xbox','call-of-duty','modern-warfare'], '/assets/portal-games-clean-v1.webp', 'Entrada futurista al portal Gaming'),
  ('gaming-xbox-denshattack', 'Denshattack mezcla trenes, velocidad y desafío arcade', 'Xbox destacó una propuesta inusual que convierte el movimiento ferroviario en una experiencia de acción estilizada.', 'https://news.xbox.com/en-us/', 'La cobertura oficial de Xbox presenta el concepto y su llegada al ecosistema.', 'Los juegos pequeños ganan identidad cuando una mecánica clara se sostiene con dirección audiovisual. No necesitan imitar una superproducción.', 'Trenes haciendo cosas imposibles: exactamente la clase de anomalía jugable que merece una misión secundaria en el Nexus.', array['xbox','indie','denshattack'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Nexus Gaming con estética anime'),
  ('gaming-xbox-gta-online-kortz', 'GTA Online abre el golpe del Kortz Center', 'Rockstar y Xbox difundieron una nueva operación para GTA Online centrada en el Kortz Center.', 'https://news.xbox.com/en-us/', 'La noticia aparece en el canal oficial de Xbox como parte de la actualización del servicio en vivo.', 'El contenido de un juego persistente depende de versión, plataforma y ventana del evento. Las recompensas promocionales pueden tener condiciones.', 'Reuní la crew, verificá el objetivo y no confundas el caos de Los Santos con instrucciones para la vida real.', array['xbox','gta-online','live-service'], '/assets/portal-games-clean-v1.webp', 'Portal violeta hacia una ciudad gamer'),
  ('gaming-xbox-free-play-days', 'Free Play Days renueva su rotación', 'Xbox mantiene su ventana temporal para probar títulos seleccionados sin comprarlos durante el período anunciado.', 'https://news.xbox.com/en-us/', 'Xbox Wire publica periódicamente la lista y las fechas de cada rotación de Free Play Days.', 'Una prueba temporal es ideal para medir rendimiento, accesibilidad y afinidad antes de comprar. El acceso puede requerir una suscripción elegible.', 'Descargá con intención: si el fin de semana se va entero instalando, el verdadero enemigo era el ancho de banda.', array['xbox','free-play-days','deals'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Héroe anime explorando el portal Gaming'),
  ('gaming-xbox-mavrix', 'MAVRIX lleva la montaña al circuito Xbox', 'Xbox Wire puso el foco en MAVRIX y su propuesta de descenso, exploración y cultura de mountain bike.', 'https://news.xbox.com/en-us/', 'El artículo oficial funciona como puerta de entrada al concepto y a su disponibilidad.', 'Los deportes de nicho pueden encontrar comunidad cuando el control transmite ritmo y riesgo sin exigir experiencia real previa.', 'Casco virtual puesto. Para la montaña real, casco real también: la fantasía suma; la seguridad no se negocia.', array['xbox','mavrix','sports'], '/assets/portal-games-clean-v1.webp', 'Energía del portal gamer de Xethkioz'),
  ('gaming-riot-kick-esports-distribution', 'Riot amplía la distribución de esports con KICK', 'Riot Games anunció una expansión de su distribución global para acercar sus competencias a nuevas audiencias en KICK.', 'https://www.riotgames.com/en/news', 'El anuncio aparece en el canal corporativo oficial de Riot y enmarca a KICK como un nuevo punto de distribución de esports.', 'Más plataformas pueden mejorar el alcance, pero horarios, derechos regionales y funciones de chat siguen dependiendo de cada transmisión concreta.', 'Para Xethkioz, que ya vive entre stream y comunidad, la señal importa: más puertas de entrada, con moderación y enlaces oficiales siempre visibles.', array['riot-games','kick','esports'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Guerrero anime recibiendo una señal de esports'),
  ('gaming-xbox-smalland-2', 'Smalland 2 vuelve a reducir la escala del mundo', 'La secuela expande la supervivencia en miniatura y Xbox la incorporó a su radar de lanzamientos.', 'https://news.xbox.com/en-us/', 'La cobertura oficial presenta el regreso de la serie y su nueva etapa.', 'Las secuelas de supervivencia deben demostrar mejoras en progresión, cooperación y rendimiento además de aumentar contenido.', 'Cuando una hormiga parece raid boss, la party necesita plan. Tamaño pequeño, amenazas gigantes, señal aprobada.', array['xbox','smalland-2','survival'], '/assets/identity/gaming-anime-nexus-v1.webp', 'Mundo de videojuegos atravesado por energía violeta')
), numbered as (
  select editorial.*, row_number() over (order by slug) as position
  from editorial
), author as (
  select id from auth.users where lower(email) = 'xethkioz@gmail.com' limit 1
)
insert into public.news_articles (
  slug, title, summary, content, category, author_id, status, published_at, tags,
  source_urls, ai_generated, review_status, editor_notes, metrics,
  cover_image_url, cover_image_alt, cover_image_path
)
select
  slug,
  title,
  summary,
  jsonb_build_array(
    jsonb_build_object('type', 'heading', 'text', 'La señal'),
    jsonb_build_object('type', 'paragraph', 'text', signal),
    jsonb_build_object('type', 'heading', 'text', 'Qué está confirmado'),
    jsonb_build_object('type', 'paragraph', 'text', context),
    jsonb_build_object('type', 'heading', 'text', 'Lectura Xethkioz'),
    jsonb_build_object('type', 'paragraph', 'text', xeth_read),
    jsonb_build_object('type', 'list', 'text', 'Fuente primaria oficial; contexto editorial; límites explícitos; lectura responsable')
  ),
  'gaming',
  (select id from author),
  'published',
  timestamptz '2026-07-17 08:00:00-03' - ((position - 1) * interval '4 hours'),
  tags || array['xethkioz','fuente-oficial'],
  array[source_url],
  true,
  'approved',
  'Biblioteca editorial XETHKIOZ 2026-07: fuente primaria verificada y revisión humana estructural.',
  jsonb_build_object('views', 0, 'likes', 0, 'shares', 0),
  cover_image_url,
  cover_image_alt,
  cover_image_url
from numbered
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  content = excluded.content,
  category = excluded.category,
  author_id = excluded.author_id,
  status = excluded.status,
  published_at = excluded.published_at,
  tags = excluded.tags,
  source_urls = excluded.source_urls,
  ai_generated = excluded.ai_generated,
  review_status = excluded.review_status,
  editor_notes = excluded.editor_notes,
  cover_image_url = excluded.cover_image_url,
  cover_image_alt = excluded.cover_image_alt,
  cover_image_path = excluded.cover_image_path,
  updated_at = now();
