-- XETHKIOZ editorial library: 30 defensive, sourced Green Node dossiers.
-- Mystery aesthetic; evidence labels remain explicit.

with editorial (
  slug, title, summary, source_url, signal, context, xeth_read, tags
) as (
  values
  ('green-security-plan', 'Expediente 01: construí tu propio modelo de amenazas', 'EFF propone empezar la seguridad identificando qué querés proteger, de quién y con qué recursos reales.', 'https://ssd.eff.org/module/your-security-plan', 'Un plan de seguridad útil define activos, adversarios posibles, consecuencias y medidas proporcionadas.', 'No existe una configuración universalmente segura. Una persona pública, un comercio y una familia enfrentan riesgos diferentes.', 'Antes del ritual técnico, dibujá el mapa: cuentas críticas, dispositivos, copias y personas que pueden ayudarte.', array['eff','threat-model','privacy']),
  ('green-strong-passwords', 'Expediente 02: contraseñas largas y únicas', 'La guía de EFF explica por qué cada servicio necesita una clave distinta y cómo un gestor reduce la carga.', 'https://ssd.eff.org/module/creating-strong-passwords', 'La reutilización permite que una filtración abra varias cuentas; longitud y unicidad reducen ese efecto dominó.', 'Una contraseña fuerte no compensa phishing, malware o recuperación de cuenta débil. Debe combinarse con segundo factor.', 'El grimorio correcto no se memoriza entero: se guarda cifrado, se respalda y nunca se pega en un chat.', array['eff','passwords','security']),
  ('green-encryption-basics', 'Expediente 03: qué protege realmente el cifrado', 'EFF separa cifrado en tránsito, cifrado del dispositivo y cifrado de extremo a extremo.', 'https://ssd.eff.org/module/what-should-i-know-about-encryption', 'Cifrar transforma información para que sólo quien posee la clave adecuada pueda leerla.', 'El cifrado protege contenido, pero puede dejar visibles metadatos como horarios, participantes o tamaño de mensajes.', 'El candado no vuelve invisible la puerta. Preguntá siempre qué se cifra, quién conserva claves y qué queda registrado.', array['eff','encryption','metadata']),
  ('green-avoid-phishing', 'Expediente 04: detectar el anzuelo antes del clic', 'La guía de EFF reúne señales y hábitos para reducir el riesgo de phishing.', 'https://ssd.eff.org/module/how-avoid-phishing-attacks', 'Mensajes urgentes, dominios parecidos y archivos inesperados buscan que la víctima actúe antes de verificar.', 'Una apariencia profesional no autentica al remitente. Las campañas modernas pueden usar contexto real y texto convincente.', 'Si el mensaje exige velocidad, frená. Abrí el servicio por tu marcador, no por el enlace que llegó desde la oscuridad.', array['eff','phishing','defense']),
  ('green-two-factor-authentication', 'Expediente 05: el segundo factor como sello adicional', 'EFF explica cómo activar 2FA y por qué una app o llave suele resistir mejor que depender sólo de SMS.', 'https://ssd.eff.org/module/how-enable-two-factor-authentication', 'El segundo factor limita el daño cuando una contraseña es robada.', 'No todos los factores ofrecen la misma resistencia y los códigos de recuperación deben almacenarse fuera del teléfono principal.', 'Activá 2FA primero en correo, banco, redes y paneles. Si perdés el correo, muchas otras puertas caen detrás.', array['eff','2fa','accounts']),
  ('green-encrypt-windows', 'Expediente 06: cifrar un equipo Windows', 'EFF documenta pasos y precauciones para proteger datos almacenados en dispositivos Windows compatibles.', 'https://ssd.eff.org/module/how-encrypt-your-windows-device', 'El cifrado de disco ayuda cuando un dispositivo se pierde o es robado y permanece bloqueado.', 'No protege una sesión abierta ni reemplaza backups. La clave de recuperación es crítica y debe guardarse de forma separada.', 'Cifrar sin respaldar la recuperación puede convertir tu defensa en tu propio bloqueo. Probá el plan antes de necesitarlo.', array['eff','windows','disk-encryption']),
  ('green-digital-footprint', 'Expediente 07: cartografiar tu huella digital', 'EFF propone revisar qué información personal existe en línea y reducir exposición innecesaria.', 'https://ssd.eff.org/module/how-to-manage-your-digital-footprint', 'Publicaciones viejas, perfiles y bases de datos pueden combinarse para identificar hábitos y relaciones.', 'Borrar una copia no garantiza eliminar todas las réplicas. La reducción de huella es un proceso continuo.', 'Buscate como lo haría un desconocido, corregí lo controlable y evitá regalar ubicación en tiempo real.', array['eff','digital-footprint','osint']),
  ('green-network-censorship', 'Expediente 08: cómo opera la censura de red', 'EFF describe técnicas de bloqueo y herramientas para sortear restricciones sin confundir anonimato con invulnerabilidad.', 'https://ssd.eff.org/module/understanding-and-circumventing-network-censorship', 'Los bloqueos pueden actuar sobre DNS, direcciones, protocolos o contenido, y cada evasión enfrenta riesgos distintos.', 'Una herramienta permitida en un país puede ser peligrosa o ilegal en otro. El contexto local importa tanto como la técnica.', 'No uses una salida clandestina sin entender quién observa la entrada, la salida y tu dispositivo.', array['eff','censorship','networks']),
  ('green-how-to-use-tor', 'Expediente 09: usar Tor sin inventar invisibilidad', 'EFF ofrece una introducción práctica a Tor Browser y a los límites de la protección que brinda.', 'https://ssd.eff.org/module/how-to-use-tor', 'Tor enruta tráfico por múltiples relés para separar origen y destino con más dificultad.', 'Iniciar sesión con identidad real, descargar archivos riesgosos o cambiar configuraciones puede reducir la protección.', 'Tor no es una capa de invisibilidad demoníaca. Es una herramienta con modelo de amenaza, hábitos y límites.', array['eff','tor','anonymity']),
  ('green-public-key-encryption', 'Expediente 10: claves públicas bajo el sigilo', 'EFF explica cómo la criptografía de clave pública permite acordar secretos y verificar identidades.', 'https://ssd.eff.org/module/deep-dive-end-end-encryption-how-do-public-key-encryption-systems-work', 'Una clave puede compartirse y otra debe permanecer secreta; su relación matemática habilita cifrado y firmas.', 'La matemática no resuelve por sí sola la confianza inicial. Verificar la clave y proteger el dispositivo sigue siendo esencial.', 'El símbolo puede ser público; el secreto no. Si no verificás a quién pertenece la clave, el ritual queda incompleto.', array['eff','public-key','cryptography']),
  ('green-choosing-vpn', 'Expediente 11: elegir una VPN sin comprar humo', 'EFF propone preguntas para evaluar proveedores según confianza, necesidad y amenaza concreta.', 'https://ssd.eff.org/module/choosing-vpn-thats-right-you', 'Una VPN mueve la confianza desde la red local hacia el proveedor y cifra el tramo hasta su servidor.', 'No garantiza anonimato total, no elimina rastreo del navegador y no vuelve seguro un dispositivo comprometido.', 'Cambiar de observador no equivale a desaparecer. Revisá política, jurisdicción, historial y razón real para usarla.', array['eff','vpn','privacy']),
  ('green-malware-defense', 'Expediente 12: defensa contra malware sin rituales falsos', 'EFF reúne medidas básicas para reducir infecciones y responder a señales de compromiso.', 'https://ssd.eff.org/module/how-do-i-protect-myself-against-malware', 'Actualizaciones, descargas confiables, permisos limitados y copias separadas reducen riesgo e impacto.', 'Un antivirus no detecta todo y una alerta aislada necesita investigación. La recuperación debe planearse antes del incidente.', 'El malware no teme calaveras verdes. Teme parches, mínimos privilegios, backups probados y usuarios que verifican.', array['eff','malware','defense']),
  ('green-browser-fingerprinting', 'Expediente 13: la huella que deja tu navegador', 'EFF explica cómo la combinación de características del navegador puede distinguir a un usuario sin cookies tradicionales.', 'https://ssd.eff.org/module/what-fingerprinting', 'Pantalla, fuentes, idioma, zona horaria y capacidades técnicas pueden formar una huella relativamente singular.', 'Bloquear cookies no elimina fingerprinting. Personalizar demasiado el navegador también puede volverlo más reconocible.', 'A veces camuflarse es parecerse al grupo, no agregar veinte amuletos distintos al navegador.', array['eff','fingerprinting','browser']),
  ('green-nist-csf-2', 'Archivo NIST: el marco que ordena la ciberseguridad', 'NIST CSF 2.0 organiza gobernanza, identificación, protección, detección, respuesta y recuperación.', 'https://www.nist.gov/cyberframework', 'El marco ofrece un lenguaje común para administrar riesgo sin imponer una única tecnología.', 'Adoptar nombres de funciones no demuestra madurez. Cada organización debe convertirlos en responsables, controles y evidencia.', 'Un mapa no detiene al intruso, pero evita que todos corran en direcciones distintas cuando aparece la señal.', array['nist','csf','risk']),
  ('green-nist-privacy-framework', 'Archivo NIST: privacidad como riesgo gestionable', 'El Privacy Framework ayuda a identificar y reducir consecuencias adversas del tratamiento de datos.', 'https://www.nist.gov/privacy-framework', 'NIST conecta actividades de datos con resultados de privacidad y decisiones organizacionales.', 'Cumplimiento legal y gestión de privacidad se relacionan, pero no son idénticos. El marco debe adaptarse a jurisdicción y contexto.', 'Preguntá qué dato entra, para qué, cuánto vive y quién puede verlo. El misterio sobra cuando el flujo está documentado.', array['nist','privacy','governance']),
  ('green-nist-password-guidance', 'Archivo NIST: una buena contraseña prioriza longitud', 'NIST recomienda claves de al menos 15 caracteres y explica por qué las frases largas pueden ser más útiles que reglas arbitrarias.', 'https://www.nist.gov/cybersecurity-and-privacy/how-do-i-create-good-password', 'La guía moderna prioriza longitud, bloqueo de claves comprometidas y facilidad de uso.', 'No recomienda abandonar toda complejidad ni usar frases conocidas. Cada contraseña debe seguir siendo única e impredecible.', 'La clave más teatral no siempre es la más fuerte. Largo, único, gestor y 2FA: menos runas, mejor defensa.', array['nist','passwords','identity']),
  ('green-nist-post-quantum', 'Archivo NIST: la transición criptográfica poscuántica', 'NIST publicó estándares para proteger intercambio de claves y firmas frente a futuros computadores cuánticos relevantes.', 'https://www.nist.gov/cybersecurity-and-privacy/what-post-quantum-cryptography', 'FIPS 203, 204 y 205 establecen algoritmos poscuánticos listos para iniciar migraciones.', 'No existe hoy evidencia pública de un computador capaz de romper a escala la criptografía moderna; migrar lleva años y los datos capturados hoy pueden conservar valor.', 'No es apocalipsis cuántico mañana: es inventario criptográfico hoy. La preparación seria empieza sin pánico.', array['nist','post-quantum','cryptography']),
  ('green-nist-pqc-standards', 'Archivo NIST: tres estándares contra la amenaza cuántica', 'NIST finalizó ML-KEM, ML-DSA y SLH-DSA para intercambio de claves y firmas resistentes a ataques cuánticos futuros.', 'https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards', 'Los estándares FIPS fueron aprobados después de un proceso público de evaluación internacional.', 'Estandarizado no significa imposible de fallar. Implementaciones, parámetros, migración y agilidad criptográfica necesitan pruebas.', 'El algoritmo es sólo una pieza del sello. Una mala integración puede romper la defensa más elegante.', array['nist','fips','pqc']),
  ('green-nist-hqc-backup', 'Archivo NIST: HQC como segunda línea poscuántica', 'NIST seleccionó HQC como alternativa de encapsulación basada en matemáticas distintas a ML-KEM.', 'https://www.nist.gov/news-events/news/2025/03/nist-selects-hqc-fifth-algorithm-post-quantum-encryption', 'HQC fue elegido para diversificar defensas y se dirige a un proceso de estandarización.', 'Todavía no reemplaza a ML-KEM ni es una orden de migración inmediata. Su valor es ofrecer diversidad si aparece una debilidad futura.', 'Un único sigilo puede quebrarse. La resiliencia también consiste en no depender de una sola familia matemática.', array['nist','hqc','pqc']),
  ('green-nist-iot-security', 'Archivo NIST: el hogar inteligente también es superficie de ataque', 'El programa de NIST para IoT reúne orientación sobre capacidades de seguridad y gestión de dispositivos conectados.', 'https://www.nist.gov/itl/applied-cybersecurity/nist-cybersecurity-iot-program', 'Inventario, actualizaciones, autenticación y soporte del fabricante son factores centrales del riesgo IoT.', 'Separar la red ayuda, pero no corrige un dispositivo abandonado o una cuenta de nube insegura.', 'Si una lámpara necesita internet, también necesita dueño, parche y fecha de retiro. Todo nodo conectado deja huella.', array['nist','iot','smart-home']),
  ('green-nist-identity-access', 'Archivo NIST: identidad digital sin atajos', 'NIST mantiene guías para autenticación, federación y niveles de garantía de identidad.', 'https://www.nist.gov/identity-access-management', 'La identidad digital combina prueba de identidad, autenticadores, recuperación y control de acceso.', 'Más datos personales no garantizan mejor seguridad. La verificación debe ser proporcional y proteger también la privacidad.', 'La pregunta no es sólo “¿quién sos?”, sino quién puede afirmarlo, cómo lo demuestra y cómo recuperás la cuenta.', array['nist','identity','authentication']),
  ('green-nasa-uap-study', 'UAP: qué investigó realmente el estudio independiente de NASA', 'NASA reunió especialistas para evaluar cómo los datos y métodos científicos pueden mejorar el estudio de fenómenos anómalos no identificados.', 'https://science.nasa.gov/uap/', 'El objetivo declarado fue recomendar una metodología de datos, no revisar cada caso histórico ni probar origen extraterrestre.', 'No identificado significa que la información disponible no basta para clasificar el fenómeno. No es una categoría de origen.', 'El archivo permanece abierto, pero la etiqueta correcta es “sin resolver”, no “confirmado”. Esa diferencia protege el misterio de la mentira.', array['nasa','uap','evidence']),
  ('green-nasa-uap-data', 'UAP: el problema central es la calidad de los datos', 'NASA señala que observaciones inconsistentes y metadatos incompletos dificultan análisis reproducibles de UAP.', 'https://science.nasa.gov/uap/', 'Para comparar casos hacen falta sensores calibrados, hora, ubicación, condiciones y formatos compatibles.', 'Muchos videos pueden ser interesantes sin contener información suficiente para calcular distancia, tamaño o velocidad.', 'Una luz sin escala es una historia; una medición con contexto puede convertirse en expediente.', array['nasa','uap','data-quality']),
  ('green-nasa-uap-stigma', 'UAP: reducir el estigma mejora el reporte, no la certeza', 'El informe de NASA plantea que reportes más abiertos pueden aumentar la cantidad y calidad de datos disponibles.', 'https://science.nasa.gov/uap/', 'Menos estigma facilita que pilotos y observadores informen eventos sin temor a ridículo.', 'Recibir más reportes también aumenta casos ambiguos. La apertura debe ir acompañada de protocolos y análisis crítico.', 'Escuchar no obliga a creer; investigar no obliga a burlarse. Green Node puede sostener ambas cosas.', array['nasa','uap','reporting']),
  ('green-nasa-uap-no-alien-evidence', 'UAP: NASA no presentó evidencia de origen extraterrestre', 'La página oficial diferencia la investigación de anomalías observadas de cualquier afirmación sobre vida alienígena.', 'https://science.nasa.gov/uap/', 'El estudio no concluyó que los UAP sean extraterrestres y pidió mejores datos para caracterizar observaciones.', 'Ausencia de evidencia no demuestra imposibilidad, pero tampoco permite llenar el vacío con una explicación favorita.', 'El protocolo de verdad queda activo: posibilidad, hipótesis y evidencia ocupan niveles distintos del archivo.', array['nasa','uap','aliens']),
  ('green-fbi-ufo-vault', 'El archivo UFO del FBI: documentos reales, interpretaciones cuidadosas', 'The Vault publica documentos desclasificados del FBI relacionados con reportes y correspondencia sobre objetos no identificados.', 'https://vault.fbi.gov/UFO', 'El repositorio es auténtico y permite consultar imágenes de documentos históricos organizados en múltiples partes.', 'Que el FBI archive un reporte no valida automáticamente su contenido. Una agencia puede registrar alegaciones sin confirmarlas.', 'Documento oficial no significa conclusión oficial. Leé autor, destinatario, fecha, cadena y resultado de la investigación.', array['fbi','ufo','documents']),
  ('green-fbi-ufo-context', 'Cómo leer un documento desclasificado sin fabricar una conspiración', 'Los archivos UFO del FBI permiten practicar análisis de procedencia, contexto y lenguaje burocrático.', 'https://vault.fbi.gov/UFO', 'Sellos, membretes y tachaduras ayudan a establecer procedencia, pero cada afirmación conserva su propio nivel de respaldo.', 'Una página aislada puede perder anexos, respuestas o contexto posterior. El documento completo y la cronología importan.', 'Seleccionar sólo la frase más oscura es buen contenido viral y mala investigación. El expediente entero manda.', array['fbi','declassified','media-literacy']),
  ('green-tor-history', 'Tor: de investigación naval a proyecto abierto', 'Tor Project relata cómo el onion routing pasó de investigación financiada públicamente a una red y organización sin fines de lucro.', 'https://www.torproject.org/about/history/', 'La historia oficial ubica los orígenes, la apertura del código y la creación del proyecto.', 'Un origen gubernamental no prueba control secreto actual, así como código abierto no garantiza ausencia de fallas.', 'La historia es extraña y verificable sin adornos. A veces la conspiración pierde fuerza cuando aparece la cronología completa.', array['tor','history','onion-routing']),
  ('green-tor-what-is', 'Tor separa origen y destino mediante relés', 'Tor Project explica el principio básico de la red y el papel de Tor Browser.', 'https://support.torproject.org/about/what-is-tor/', 'El tráfico recorre una ruta de relés y cada salto conoce sólo una parte necesaria del circuito.', 'La red no cifra mágicamente fuera de su salida ni protege una identidad que el usuario revela voluntariamente.', 'Capas de cebolla, no capa de invisibilidad. El modelo funciona mejor cuando el comportamiento acompaña a la herramienta.', array['tor','onion-routing','privacy']),
  ('green-tor-myths-limits', 'Tor: límites que el mito suele borrar', 'La documentación oficial insiste en que Tor reduce ciertos rastreos, pero no resuelve malware, errores humanos ni toda vigilancia.', 'https://support.torproject.org/about/what-is-tor/', 'La protección depende de usar software actualizado y de no alterar hábitos de forma que revelen identidad.', 'Adversarios con observación amplia y dispositivos comprometidos quedan fuera de muchas garantías prácticas.', 'La herramienta es real; la omnipotencia no. Un archivo serio conserva ambos datos en la misma pantalla.', array['tor','limits','opsec'])
), numbered as (
  select editorial.*, row_number() over (order by slug) as position from editorial
), author as (
  select id from auth.users where lower(email)='xethkioz@gmail.com' limit 1
)
insert into public.news_articles (
  slug,title,summary,content,category,author_id,status,published_at,tags,source_urls,
  ai_generated,review_status,editor_notes,metrics,cover_image_url,cover_image_alt,cover_image_path
)
select slug,title,summary,
  jsonb_build_array(
    jsonb_build_object('type','heading','text','SEÑAL INTERCEPTADA'),
    jsonb_build_object('type','paragraph','text',signal),
    jsonb_build_object('type','heading','text','EVIDENCIA / LÍMITE'),
    jsonb_build_object('type','paragraph','text',context),
    jsonb_build_object('type','heading','text','LECTURA XETHKIOZ'),
    jsonb_build_object('type','paragraph','text',xeth_read),
    jsonb_build_object('type','list','text','Fuente primaria; dato confirmado; límite explícito; práctica defensiva')
  ), 'green', (select id from author), 'published',
  timestamptz '2026-07-17 07:00:00-03' - ((position-1)*interval '6 hours'),
  tags||array['xethkioz','green-node','fuente-oficial'], array[source_url], true, 'approved',
  'Biblioteca editorial XETHKIOZ 2026-07: archivo defensivo con fuente primaria y protocolo de evidencia.',
  jsonb_build_object('views',0,'likes',0,'shares',0),
  '/assets/identity/green-node-occult-malware-v1.webp',
  'Entidad digital del Green Node rodeada de código, sigilos y energía verde',
  '/assets/identity/green-node-occult-malware-v1.webp'
from numbered
on conflict (slug) do update set
  title=excluded.title,summary=excluded.summary,content=excluded.content,category=excluded.category,
  author_id=excluded.author_id,status=excluded.status,published_at=excluded.published_at,
  tags=excluded.tags,source_urls=excluded.source_urls,ai_generated=excluded.ai_generated,
  review_status=excluded.review_status,editor_notes=excluded.editor_notes,
  cover_image_url=excluded.cover_image_url,cover_image_alt=excluded.cover_image_alt,
  cover_image_path=excluded.cover_image_path,updated_at=now();
