-- XETHKIOZ editorial library: 30 sourced Science & Technology dossiers.

with editorial (
  slug, title, summary, category, source_url, signal, context, xeth_read, tags, cover_image_url, cover_image_alt
) as (
  values
  ('science-artemis-iii-lander-test', 'Artemis III ensaya el regreso humano a la Luna', 'NASA explica cómo una prueba del módulo de alunizaje prepara procedimientos críticos para futuras misiones tripuladas.', 'science', 'https://www.nasa.gov/directorates/esdmd/artemis-campaign-development-division/human-landing-system-program/how-nasas-artemis-iii-lander-test-will-pave-way-for-moon-landings/', 'La prueba oficial del sistema de alunizaje busca reducir incertidumbre antes de transportar astronautas a la superficie lunar.', 'Un ensayo no equivale a una misión completa: valida interfaces, operaciones y respuestas concretas dentro de condiciones controladas.', 'La exploración espacial se construye como una buena web: sistemas separados, pruebas repetibles y cero fe ciega en que todo funcionará junto a la primera.', array['nasa','artemis','moon'], '/assets/portal-science-clean-v1.webp', 'Portal azul de ciencia y tecnología con planeta holográfico'),
  ('science-perseverance-ancient-impacts', 'Perseverance lee impactos en la memoria de Marte', 'El rover de NASA analiza rocas que conservan un registro de antiguos impactos sobre la superficie marciana.', 'science', 'https://www.nasa.gov/solar-system/planets/mars/nasas-perseverance-rover-reads-record-of-ancient-mars-impacts/', 'Las observaciones de Perseverance permiten reconstruir episodios de impacto registrados en materiales del cráter Jezero.', 'La edad y el origen de una roca se infieren combinando textura, química, contexto geológico y modelos; una imagen aislada no resuelve toda la historia.', 'Marte no entrega respuestas: entrega fragmentos. El laboratorio Xethkioz los trata como evidencia, nunca como decoración alienígena.', array['nasa','mars','perseverance'], '/assets/portal-science-clean-v1.webp', 'Laboratorio futurista azul con una esfera planetaria'),
  ('science-webb-hidden-planet', 'Webb descubre un planeta oculto en un sistema famoso', 'NASA informó que el telescopio James Webb identificó un planeta que había permanecido escondido dentro de un sistema estelar conocido.', 'science', 'https://science.nasa.gov/missions/webb/nasas-webb-discovers-hidden-planet-in-famous-star-system/', 'La detección se apoya en la capacidad infrarroja y el análisis del sistema por parte del equipo científico de Webb.', 'Descubrir no significa fotografiar como una cámara común: muchas detecciones dependen de separar señales débiles de la luz estelar y contrastarlas con modelos.', 'Cuando una señal aparece detrás del ruido, el trabajo recién empieza. El titular abre el portal; los datos sostienen el viaje.', array['nasa','webb','exoplanet'], '/assets/portal-science-clean-v1.webp', 'Planeta azul observado desde un laboratorio tecnológico'),
  ('science-davinci-venus-helicopter', 'Un helicóptero en Utah prueba instrumentos rumbo a Venus', 'El equipo DAVINCI de NASA utilizó vuelos sobre Utah para probar observaciones que ayudarán a estudiar Venus.', 'science', 'https://science.nasa.gov/blogs/planetary-expeditions/2026/07/14/utah-helicopter-flights-test-nasas-davinci-mission-to-venus/', 'Los vuelos recrean geometrías y condiciones de observación útiles para preparar la futura misión DAVINCI.', 'Una campaña terrestre no reproduce Venus por completo; permite calibrar instrumentos, procesos y lectura de paisajes con referencias conocidas.', 'Antes de descender a otro planeta, el laboratorio practica en casa. Ciencia real: menos magia, más calibración.', array['nasa','venus','davinci'], '/assets/portal-science-clean-v1.webp', 'Portal científico azul con instrumentos de exploración'),
  ('science-roman-black-holes-shred-stars', 'Roman buscará agujeros negros que destruyen estrellas', 'NASA anticipa cómo el telescopio Nancy Grace Roman detectará eventos de disrupción de marea en regiones lejanas.', 'science', 'https://www.nasa.gov/missions/roman-space-telescope/nasas-roman-telescope-will-spot-distant-black-holes-that-shred-stars/', 'La amplitud de campo de Roman permitirá vigilar grandes regiones y encontrar destellos asociados a estrellas desgarradas por agujeros negros.', 'El observatorio todavía debe operar y producir datos; la nota describe capacidad esperada, no un catálogo ya obtenido.', 'El cosmos tiene estética de jefe final, pero la detección se gana con cadencia, comparación y paciencia.', array['nasa','roman','black-holes'], '/assets/portal-science-clean-v1.webp', 'Esfera cósmica dentro del portal de ciencia'),
  ('science-ontario-wildfire-smoke', 'El humo de incendios de Ontario se desplaza al este', 'El Observatorio de la Tierra de NASA documentó mediante satélites la extensión del humo y su transporte atmosférico.', 'science', 'https://science.nasa.gov/earth/earth-observatory/ontario-wildfire-smoke-moves-east/', 'Los sensores orbitales ofrecen una vista regional del penacho y de su evolución.', 'Una imagen satelital muestra distribución, pero las decisiones sanitarias locales deben apoyarse en mediciones de calidad del aire y organismos competentes.', 'Desde arriba la señal parece hermosa; abajo puede ser peligrosa. Contexto y escala cambian el significado de una imagen.', array['nasa','earth','wildfires'], '/assets/portal-science-clean-v1.webp', 'Planeta observado mediante tecnología azul'),
  ('science-heat-dome-western-us', 'Una cúpula de calor castiga el oeste de Estados Unidos', 'NASA Earth Observatory explica el patrón atmosférico detrás de un episodio de calor extremo.', 'science', 'https://science.nasa.gov/earth/earth-observatory/heat-dome-broils-the-western-u-s/', 'Los datos muestran temperaturas y una configuración persistente de alta presión asociada al evento.', 'El concepto de cúpula de calor describe un patrón meteorológico; no es una cubierta física ni explica por sí solo cada impacto local.', 'Los mapas térmicos son alertas, no wallpapers. Ante calor extremo mandan los servicios meteorológicos y sanitarios locales.', array['nasa','climate','heat'], '/assets/portal-science-clean-v1.webp', 'Laboratorio azul analizando el planeta Tierra'),
  ('science-pristine-meteorite-asteroids', 'Un meteorito prístino amplía la historia de los asteroides', 'NASA estudió material poco alterado para reconstruir procesos tempranos del sistema solar.', 'science', 'https://science.nasa.gov/science-research/astromaterials/nasa-study-of-pristine-meteorite-adds-to-story-of-ancient-asteroids/', 'La preservación del material permite analizar componentes que podrían haberse modificado en muestras más expuestas.', 'Prístino significa excepcionalmente bien conservado dentro de criterios científicos, no intacto en sentido absoluto.', 'Una piedra puede ser un archivo más antiguo que internet. La clave no es mirarla: es conservar cadena de custodia y medirla bien.', array['nasa','meteorite','asteroids'], '/assets/portal-science-clean-v1.webp', 'Núcleo planetario azul dentro del laboratorio Xethkioz'),
  ('science-hubble-clusters-missing-black-holes', 'Hubble encuentra cúmulos donde faltan agujeros negros', 'NASA reportó una primera detección de cúmulos estelares con una ausencia inesperada de agujeros negros.', 'science', 'https://science.nasa.gov/missions/hubble/nasas-hubble-discovers-first-of-star-clusters-missing-black-holes/', 'El hallazgo surge de observaciones y dinámica estelar que permiten estimar qué masa compacta permanece en los cúmulos.', 'La ausencia científica se establece contra una expectativa medible; no significa que se haya observado literalmente un vacío con etiqueta.', 'A veces la anomalía no es lo que aparece, sino lo que debería estar. Green Node toma nota; Ciencia calcula.', array['nasa','hubble','star-clusters'], '/assets/portal-science-clean-v1.webp', 'Observatorio digital azul con esfera espacial'),
  ('science-subscale-aircraft-innovation', 'NASA acelera innovación con aeronaves a subescala', 'El centro Armstrong usa modelos voladores más pequeños para probar ideas antes de llevarlas a aeronaves mayores.', 'tech', 'https://www.nasa.gov/centers-and-facilities/armstrong/nasa-uses-subscale-aircraft-to-accelerate-flight-innovation/', 'Las plataformas subescala reducen costo y riesgo durante etapas tempranas de investigación de vuelo.', 'Escalar un resultado requiere validar aerodinámica, control y materiales; un modelo no replica automáticamente todos los fenómenos del vehículo final.', 'Prototipo pequeño, aprendizaje grande. Es la misma lógica que evita romper producción por probar una idea directamente en vivo.', array['nasa','aviation','prototype'], '/assets/portal-science-clean-v1.webp', 'Tecnología robótica dentro de un portal azul'),
  ('science-smoother-air-taxi-rides', 'NASA estudia cómo suavizar los viajes en taxi aéreo', 'Una investigación de NASA analiza qué movimientos resultan aceptables para pasajeros de futuras aeronaves urbanas.', 'science', 'https://www.nasa.gov/centers-and-facilities/armstrong/nasa-study-points-to-smoother-air-taxi-rides/', 'El estudio conecta perfiles de movimiento con percepción humana para informar el diseño de operaciones y control.', 'Comodidad no es el único criterio: seguridad, ruido, certificación e infraestructura siguen siendo barreras independientes.', 'El futuro no alcanza con volar; tiene que hacerlo sin convertir cada viaje en una pelea contra el estómago.', array['nasa','air-taxi','human-factors'], '/assets/portal-science-clean-v1.webp', 'Laboratorio tecnológico de movilidad aérea'),
  ('science-s5-solar-sail-sentinel', 'S5 prepara una vela solar para vigilar tormentas espaciales', 'NASA desarrolla Space Storm Solar Sail Sentinel para observar el Sol desde una posición útil para alertas tempranas.', 'science', 'https://www.nasa.gov/space-storm-solar-sail-sentinel-s5/', 'La misión combina propulsión por vela solar y observación del clima espacial.', 'Una vela solar aprovecha presión de radiación; no funciona como una vela de viento terrestre. Su valor depende de trayectoria, instrumentos y comunicaciones.', 'Energía del Sol usada para vigilar al Sol: elegante, extraño y completamente físico.', array['nasa','solar-sail','space-weather'], '/assets/portal-science-clean-v1.webp', 'Esfera solar azul y energía tecnológica'),
  ('science-swift-servicing-commissioning', 'La misión de servicio a Swift avanza en su puesta en marcha', 'NASA informó que la comisión de la nave destinada a reforzar las capacidades de Swift continúa según el plan.', 'science', 'https://science.nasa.gov/blogs/swift/2026/07/15/spacecraft-commissioning-on-track-for-mission-to-boost-nasas-swift/', 'La fase de commissioning verifica sistemas antes de declarar la nave lista para su objetivo operativo.', 'Estar en trayectoria no equivale a estar plenamente operativo. Cada subsistema debe pasar comprobaciones y cualquier anomalía puede cambiar el calendario.', 'En el espacio también existe el checklist. La diferencia es que reiniciar el router queda bastante más lejos.', array['nasa','swift','spacecraft'], '/assets/portal-science-clean-v1.webp', 'Centro de control azul del portal científico'),
  ('science-curiosity-ancient-sandstorm', 'Curiosity encuentra huellas de una antigua tormenta de arena', 'Una imagen y su contexto geológico revelan estructuras que NASA interpreta como evidencia de actividad eólica pasada en Marte.', 'science', 'https://science.nasa.gov/photojournal/curiosity-finds-evidence-of-an-ancient-sandstorm/', 'Las formas observadas por Curiosity se comparan con procesos sedimentarios conocidos para reconstruir el ambiente antiguo.', 'La interpretación geológica trabaja con hipótesis contrastables; “tormenta” resume un proceso inferido, no un video del evento.', 'Marte dejó logs en piedra. Curiosity no adivina: lee patrones y los compara con física conocida.', array['nasa','curiosity','mars'], '/assets/portal-science-clean-v1.webp', 'Paisaje planetario en el laboratorio azul'),
  ('science-solar-storm-effects', 'Un estudio de NASA amplía el límite de las tormentas solares', 'NASA analiza evidencia que sugiere que los efectos de grandes tormentas solares podrían superar estimaciones habituales.', 'science', 'https://science.nasa.gov/blogs/science-news/2026/07/15/new-nasa-study-says-possibly-no-limit-to-solar-storm-effects/', 'El trabajo revisa cómo eventos extremos pueden afectar entornos espaciales y sistemas tecnológicos.', 'La frase “posiblemente sin límite” expresa una discusión científica sobre escalas y observaciones, no una predicción de catástrofe inmediata.', 'Titular potente, lectura serena: el clima espacial importa por satélites, navegación y redes; el miedo no mejora el modelo.', array['nasa','solar-storm','space-weather'], '/assets/portal-science-clean-v1.webp', 'Energía solar alrededor de un planeta holográfico'),
  ('science-citizen-record-louisiana-rainfall', 'Ciencia ciudadana registra lluvia récord en Louisiana', 'NASA destacó la medición de una persona voluntaria dentro de una red de observación de precipitaciones.', 'science', 'https://science.nasa.gov/get-involved/citizen-science/volunteer-measures-record-louisiana-rainfall/', 'El registro muestra cómo protocolos accesibles pueden aportar datos locales valiosos a redes científicas.', 'Una medición extraordinaria necesita instrumento, ubicación, hora y validación. La participación abierta funciona porque el método es compartido.', 'No hace falta un laboratorio orbital para aportar evidencia: hace falta medir bien y dejar trazabilidad.', array['nasa','citizen-science','rainfall'], '/assets/portal-science-clean-v1.webp', 'Datos del clima dentro del portal de ciencia'),
  ('ai-openai-safe-access-teens', 'OpenAI propone acceso seguro a IA para adolescentes', 'OpenAI expone su posición sobre por qué los jóvenes necesitan acceso acompañado por salvaguardas y diseño apropiado.', 'ai', 'https://openai.com/index/why-teens-deserve-access-safe-ai/', 'La publicación oficial describe principios y medidas que la empresa considera necesarias para un uso adolescente más seguro.', 'Es una posición del proveedor, no evidencia independiente de que todo riesgo esté resuelto. Familias, escuelas y reguladores deben evaluar resultados reales.', 'La IA puede ser herramienta de estudio, pero nunca debe pedir secretos, reemplazar ayuda adulta ni decidir sola en temas sensibles.', array['openai','ai-safety','teens'], '/assets/portal-science-clean-v1.webp', 'Interfaz de inteligencia artificial dentro del portal azul'),
  ('ai-openai-gpt-red-self-improvement', 'GPT-RED investiga la auto-mejora de modelos', 'OpenAI presentó trabajo sobre capacidades de auto-mejora y los controles necesarios para estudiarlas.', 'ai', 'https://openai.com/index/unlocking-self-improvement-gpt-red/', 'La fuente oficial explica el marco del experimento y la motivación de seguridad detrás de GPT-RED.', 'Una demostración de laboratorio no implica autonomía ilimitada. Alcance, herramientas, permisos y evaluación determinan lo que el sistema realmente puede hacer.', 'Menos demonio omnipotente, más threat model: qué acceso tuvo, qué objetivo recibió y quién verificó el resultado.', array['openai','gpt-red','research'], '/assets/portal-science-clean-v1.webp', 'Laboratorio de IA con energía azul'),
  ('ai-openai-agentic-investments', 'Cómo administrar inversiones de IA en la era de agentes', 'OpenAI analiza la transición desde asistentes puntuales hacia sistemas que ejecutan flujos de trabajo más extensos.', 'ai', 'https://openai.com/index/managing-ai-investments-in-agentic-era/', 'El artículo corporativo propone criterios para priorizar y gobernar inversiones en soluciones agenticas.', 'Es orientación de un proveedor con interés comercial. Sus recomendaciones deben contrastarse con costo total, dependencia, seguridad y valor medido.', 'Un agente útil no es el que hace más ruido: es el que deja logs, límites, aprobación y una salida reversible.', array['openai','agents','business'], '/assets/portal-science-clean-v1.webp', 'Agente digital representado en un laboratorio azul'),
  ('ai-gpt-56-microsoft-365-copilot', 'GPT-5.6 llega como modelo preferido a Microsoft 365 Copilot', 'OpenAI anunció la integración preferente de GPT-5.6 dentro de experiencias de Microsoft 365 Copilot.', 'ai', 'https://openai.com/index/gpt-5-6-preferred-model-microsoft-365-copilot/', 'La comunicación oficial vincula el modelo con tareas de productividad dentro del ecosistema de Microsoft.', 'Modelo preferido no significa correcto por defecto. Documentos empresariales requieren permisos mínimos, políticas de datos y revisión humana.', 'La productividad real no se mide por texto generado, sino por trabajo correcto que no expone información ni crea retrabajo.', array['openai','gpt-5.6','microsoft'], '/assets/portal-science-clean-v1.webp', 'Núcleo de IA azul conectado a herramientas digitales'),
  ('ai-openai-bio-bug-bounty', 'Un bug bounty apunta a riesgos biológicos de IA', 'OpenAI lanzó un programa para buscar fallas y escenarios de riesgo en evaluaciones de bioseguridad.', 'ai', 'https://openai.com/index/bio-bug-bounty/', 'El programa oficial invita a investigación responsable bajo condiciones y alcance definidos.', 'Un bounty complementa, pero no reemplaza, evaluaciones internas, revisión externa y gobernanza. La divulgación debe respetar reglas para no amplificar daño.', 'Premiar a quien encuentra una grieta antes que un atacante es defensa; publicar instrucciones peligrosas sin control no lo es.', array['openai','bug-bounty','biosecurity'], '/assets/portal-science-clean-v1.webp', 'Escudo digital protegiendo un laboratorio de IA'),
  ('ai-openai-gpt-56', 'GPT-5.6: capacidades, límites y evaluación', 'OpenAI publicó la ficha de su nuevo modelo con mejoras declaradas y resultados de evaluación.', 'ai', 'https://openai.com/index/gpt-5-6/', 'La página oficial es la referencia primaria para disponibilidad, modalidades y métricas reportadas por el proveedor.', 'Los benchmarks del creador son un punto de partida. Cada proyecto debe probar su propio idioma, dominio, costo, latencia y tasa de error.', 'No elijas modelo por aura. Armá un set real de tareas, ocultá las respuestas esperadas y medí antes de migrar.', array['openai','gpt-5.6','evaluation'], '/assets/portal-science-clean-v1.webp', 'Modelo de IA evaluado en el laboratorio Xethkioz'),
  ('ai-chatgpt-ambitious-work', 'ChatGPT apunta al trabajo más ambicioso', 'OpenAI presentó una evolución de ChatGPT orientada a proyectos complejos y flujos de trabajo prolongados.', 'ai', 'https://openai.com/index/chatgpt-for-your-most-ambitious-work/', 'La comunicación oficial describe la visión del producto y las capacidades que busca reunir.', 'Una plataforma más capaz también aumenta el impacto de errores y permisos excesivos. El usuario sigue siendo responsable del resultado y de los datos que entrega.', 'Dale contexto, no secretos. Delegá borradores, no criterio. Y conservá siempre una fuente de verdad fuera del chat.', array['openai','chatgpt','productivity'], '/assets/portal-science-clean-v1.webp', 'Asistente digital dentro de una interfaz tecnológica azul'),
  ('ai-openai-coding-evaluations', 'Separar señal de ruido en evaluaciones de código', 'OpenAI explica problemas frecuentes de los benchmarks de programación y cómo mejorar su capacidad de medir progreso real.', 'ai', 'https://openai.com/index/separating-signal-from-noise-coding-evaluations/', 'El artículo oficial discute contaminación, variabilidad y diseño de tareas en evaluaciones de coding.', 'Un puntaje agregado puede ocultar fallas de seguridad, mantenimiento o comprensión del repositorio. Evaluar requiere casos representativos y revisión del cambio final.', 'Si el benchmark dice “perfecto” pero rompe producción, el benchmark era el meme. Tests, diff y comportamiento mandan.', array['openai','coding','benchmarks'], '/assets/portal-science-clean-v1.webp', 'Código y métricas dentro del laboratorio de ciencia'),
  ('ai-deepmind-bioresilience', 'DeepMind define su enfoque de biorresiliencia', 'Google DeepMind detalla cómo pretende reducir riesgos biológicos y apoyar usos beneficiosos de la inteligencia artificial.', 'ai', 'https://deepmind.google/blog/our-approach-to-bioresilience/', 'La publicación oficial presenta capas de evaluación, mitigación y colaboración alrededor de capacidades biológicas.', 'Es un marco declarado por el desarrollador; su eficacia depende de implementación, auditoría y respuesta cuando aparezcan capacidades nuevas.', 'La seguridad no es un sello al final del proyecto. Tiene que vivir en datos, acceso, evaluación y monitoreo.', array['deepmind','bioresilience','ai-safety'], '/assets/portal-science-clean-v1.webp', 'Laboratorio biotecnológico protegido por energía azul'),
  ('ai-deepmind-agent-security', 'DeepMind plantea cómo asegurar el futuro de los agentes', 'El laboratorio analiza amenazas que surgen cuando los sistemas de IA obtienen herramientas, memoria y capacidad de actuar.', 'ai', 'https://deepmind.google/blog/securing-the-future-of-ai-agents/', 'La fuente oficial organiza riesgos y líneas de defensa para arquitecturas agenticas.', 'La agencia no es una propiedad mágica: surge de permisos, bucles, herramientas y objetivos. Reducir privilegios limita el daño de una decisión incorrecta.', 'Un agente con acceso total es un Wisp sin contención. Sandboxing, aprobación y registros son parte del diseño, no accesorios.', array['deepmind','agents','security'], '/assets/portal-science-clean-v1.webp', 'Entidad de IA contenida en un laboratorio digital'),
  ('ai-deepmind-multi-agent-safety', 'Nueva inversión en seguridad multiagente', 'Google DeepMind anunció apoyo a investigación sobre sistemas donde múltiples agentes de IA interactúan y compiten.', 'ai', 'https://deepmind.google/blog/investing-in-multi-agent-ai-safety-research/', 'El programa oficial reconoce que interacciones entre agentes pueden producir fallas distintas a las de un modelo aislado.', 'Más agentes no garantizan más inteligencia ni más seguridad. Pueden amplificar errores, coludir o generar costos difíciles de controlar.', 'La party necesita roles, límites y un líder humano. Cinco bots discutiendo no forman automáticamente un consejo sabio.', array['deepmind','multi-agent','safety'], '/assets/portal-science-clean-v1.webp', 'Múltiples agentes conectados en el portal de tecnología'),
  ('tech-diffusion-gemma-text-generation', 'Diffusion Gemma explora generación de texto más rápida', 'Google presentó una variante experimental que aplica ideas de difusión para acelerar generación de lenguaje.', 'tech', 'https://blog.google/innovation-and-ai/technology/developers-tools/diffusion-gemma-faster-text-generation/', 'El anuncio oficial explica el enfoque y las herramientas disponibles para desarrolladores.', 'Una arquitectura prometedora debe evaluarse por calidad, latencia real, memoria, hardware y soporte. Velocidad de laboratorio no asegura ventaja universal.', 'Otra forma de generar texto entra al portal. La pregunta útil sigue siendo la misma: ¿mejora tu tarea concreta?', array['google','gemma','diffusion'], '/assets/portal-science-clean-v1.webp', 'Flujo de datos azul generando texto con IA'),
  ('ai-gemma-4-12b', 'Gemma 4 12B amplía la familia abierta de Google', 'Google anunció Gemma 4 12B para desarrolladores que necesitan un modelo adaptable dentro de sus propios flujos.', 'ai', 'https://blog.google/innovation-and-ai/technology/developers-tools/introducing-gemma-4-12b/', 'La ficha oficial presenta tamaño, disponibilidad y usos previstos del modelo.', 'Pesos accesibles no eliminan costos de infraestructura, licencias, evaluación ni moderación. “Abierto” debe leerse según los términos concretos.', 'Modelo local o alojado: registrá versión, prompt, cuantización y hardware. Sin esos datos, comparar resultados es folklore.', array['google','gemma-4','open-model'], '/assets/portal-science-clean-v1.webp', 'Modelo abierto dentro de un laboratorio azul'),
  ('ai-deepmind-co-scientist', 'Co-Scientist coordina agentes para acelerar investigación', 'Google DeepMind presenta un sistema multiagente diseñado para proponer, debatir y priorizar hipótesis científicas.', 'ai', 'https://deepmind.google/blog/co-scientist-a-multi-agent-ai-partner-to-accelerate-research/', 'La publicación oficial describe la arquitectura y ejemplos de colaboración con investigadores.', 'Generar hipótesis no las vuelve verdaderas. Experimentos, datos, replicación y revisión siguen siendo el filtro que convierte una idea en conocimiento.', 'La IA puede llenar la pizarra; la realidad decide qué sobrevive. Ese límite hace que la herramienta sea interesante y no un oráculo.', array['deepmind','co-scientist','research'], '/assets/portal-science-clean-v1.webp', 'Científicos y agentes de IA alrededor de un núcleo azul')
), numbered as (
  select editorial.*, row_number() over (order by slug) as position
  from editorial
), author as (
  select id from auth.users where lower(email) = 'xethkioz@gmail.com' limit 1
)
insert into public.news_articles (
  slug, title, summary, content, category, author_id, status, published_at, tags,
  source_urls, ai_generated, review_status, editor_notes, metrics,
  cover_image_url, cover_image_alt, cover_image_path
)
select slug, title, summary,
  jsonb_build_array(
    jsonb_build_object('type', 'heading', 'text', 'La señal'),
    jsonb_build_object('type', 'paragraph', 'text', signal),
    jsonb_build_object('type', 'heading', 'text', 'Qué está confirmado'),
    jsonb_build_object('type', 'paragraph', 'text', context),
    jsonb_build_object('type', 'heading', 'text', 'Lectura Xethkioz'),
    jsonb_build_object('type', 'paragraph', 'text', xeth_read),
    jsonb_build_object('type', 'list', 'text', 'Fuente primaria oficial; contexto científico; límites explícitos; lectura responsable')
  ), category, (select id from author), 'published',
  timestamptz '2026-07-17 07:30:00-03' - ((position - 1) * interval '5 hours'),
  tags || array['xethkioz','fuente-oficial'], array[source_url], true, 'approved',
  'Biblioteca editorial XETHKIOZ 2026-07: fuente primaria verificada y revisión humana estructural.',
  jsonb_build_object('views', 0, 'likes', 0, 'shares', 0), cover_image_url, cover_image_alt, cover_image_url
from numbered
on conflict (slug) do update set
  title=excluded.title, summary=excluded.summary, content=excluded.content, category=excluded.category,
  author_id=excluded.author_id, status=excluded.status, published_at=excluded.published_at,
  tags=excluded.tags, source_urls=excluded.source_urls, ai_generated=excluded.ai_generated,
  review_status=excluded.review_status, editor_notes=excluded.editor_notes,
  cover_image_url=excluded.cover_image_url, cover_image_alt=excluded.cover_image_alt,
  cover_image_path=excluded.cover_image_path, updated_at=now();
