-- XETHKIOZ demo news seed
-- Carga 5 noticias demo por bloque principal para probar listado, CMS y publicador.
-- Ejecutar manualmente en Supabase SQL Editor. Es seguro de repetir por slug.

INSERT INTO public.news_articles
  (slug, title, summary, content, category, status, tags, source_urls, ai_generated, review_status, published_at)
VALUES
  ('gaming-radar-demo-01', 'Radar gamer: MMORPG de mundo abierto ganan espacio', 'Demo publicado para validar la sección Juegos con noticias categorizadas.', '[{"type":"heading","text":"Radar gamer: MMORPG de mundo abierto ganan espacio"},{"type":"paragraph","text":"Demo publicado para validar la sección Juegos con noticias categorizadas."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'gaming', 'published', ARRAY['gaming','radar','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('gaming-guides-demo-02', 'Guías y builds: clases recomendadas para empezar', 'Demo publicado para probar bloques de guías, tops y comparativas.', '[{"type":"heading","text":"Guías y builds: clases recomendadas para empezar"},{"type":"paragraph","text":"Demo publicado para probar bloques de guías, tops y comparativas."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'gaming', 'published', ARRAY['gaming','guides','builds','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('gaming-asia-demo-03', 'Asia Gaming: señales tempranas desde Corea y Japón', 'Demo publicado para probar cobertura asiática dentro del portal gaming.', '[{"type":"heading","text":"Asia Gaming: señales tempranas desde Corea y Japón"},{"type":"paragraph","text":"Demo publicado para probar cobertura asiática dentro del portal gaming."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'gaming', 'published', ARRAY['gaming','asia','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('gaming-stream-demo-04', 'Streaming gamer: clips cortos con mejor retención', 'Demo publicado para probar noticias vinculadas a Twitch, Kick y Shorts.', '[{"type":"heading","text":"Streaming gamer: clips cortos con mejor retención"},{"type":"paragraph","text":"Demo publicado para probar noticias vinculadas a Twitch, Kick y Shorts."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'gaming', 'published', ARRAY['gaming','streaming','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('gaming-mobile-demo-05', 'Mobile competitivo: comunidad y torneos rápidos', 'Demo publicado para validar cobertura mobile y esports.', '[{"type":"heading","text":"Mobile competitivo: comunidad y torneos rápidos"},{"type":"paragraph","text":"Demo publicado para validar cobertura mobile y esports."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'gaming', 'published', ARRAY['gaming','mobile','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('science-lab-demo-01', 'Ciencia: evidencia, hipótesis y contexto', 'Demo publicado para validar lectura científica sin mezclar hechos con teorías.', '[{"type":"heading","text":"Ciencia: evidencia, hipótesis y contexto"},{"type":"paragraph","text":"Demo publicado para validar lectura científica sin mezclar hechos con teorías."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'science', 'published', ARRAY['science','evidence','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('science-data-demo-02', 'Datos abiertos para investigar mejor', 'Demo publicado para probar noticias de datasets, archivo y metodología.', '[{"type":"heading","text":"Datos abiertos para investigar mejor"},{"type":"paragraph","text":"Demo publicado para probar noticias de datasets, archivo y metodología."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'science', 'published', ARRAY['science','data','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('science-visual-demo-03', 'Ciencia visual sin saturar al lector', 'Demo publicado para validar piezas explicativas y gráficas simples.', '[{"type":"heading","text":"Ciencia visual sin saturar al lector"},{"type":"paragraph","text":"Demo publicado para validar piezas explicativas y gráficas simples."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'science', 'published', ARRAY['science','visual','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('science-critical-demo-04', 'Pensamiento crítico para noticias virales', 'Demo publicado para separar fuente, copia, rumor y conclusión.', '[{"type":"heading","text":"Pensamiento crítico para noticias virales"},{"type":"paragraph","text":"Demo publicado para separar fuente, copia, rumor y conclusión."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'science', 'published', ARRAY['science','critical-thinking','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('science-outreach-demo-05', 'Divulgación para comunidad gamer', 'Demo publicado para conectar ciencia con tecnología cotidiana.', '[{"type":"heading","text":"Divulgación para comunidad gamer"},{"type":"paragraph","text":"Demo publicado para conectar ciencia con tecnología cotidiana."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'science', 'published', ARRAY['science','outreach','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('ai-local-demo-01', 'IA local para creadores independientes', 'Demo publicado para probar cobertura de modelos locales y hardware real.', '[{"type":"heading","text":"IA local para creadores independientes"},{"type":"paragraph","text":"Demo publicado para probar cobertura de modelos locales y hardware real."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'ai', 'published', ARRAY['ai','local','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('ai-prompts-demo-02', 'Prompts como sistema de trabajo', 'Demo publicado para validar noticias sobre automatización y documentación.', '[{"type":"heading","text":"Prompts como sistema de trabajo"},{"type":"paragraph","text":"Demo publicado para validar noticias sobre automatización y documentación."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'ai', 'published', ARRAY['ai','prompts','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('ai-news-demo-03', 'IA y noticias: verificación primero', 'Demo publicado para probar cobertura responsable de imágenes y fuentes.', '[{"type":"heading","text":"IA y noticias: verificación primero"},{"type":"paragraph","text":"Demo publicado para probar cobertura responsable de imágenes y fuentes."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'ai', 'published', ARRAY['ai','news','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('ai-workflow-demo-04', 'Automatización con revisión humana', 'Demo publicado para validar flujos editoriales asistidos por IA.', '[{"type":"heading","text":"Automatización con revisión humana"},{"type":"paragraph","text":"Demo publicado para validar flujos editoriales asistidos por IA."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'ai', 'published', ARRAY['ai','workflow','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('ai-lightweight-demo-05', 'Modelos livianos en PCs de consumo', 'Demo publicado para probar noticias de rendimiento y utilidad práctica.', '[{"type":"heading","text":"Modelos livianos en PCs de consumo"},{"type":"paragraph","text":"Demo publicado para probar noticias de rendimiento y utilidad práctica."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'ai', 'published', ARRAY['ai','models','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('tech-gpu-demo-01', 'GPUs entre gaming, IA y creación', 'Demo publicado para validar tecnología y hardware dentro del ecosistema.', '[{"type":"heading","text":"GPUs entre gaming, IA y creación"},{"type":"paragraph","text":"Demo publicado para validar tecnología y hardware dentro del ecosistema."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'tech', 'published', ARRAY['tech','gpu','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('tech-stream-demo-02', 'Streaming estable con bajo ruido técnico', 'Demo publicado para probar guías técnicas de transmisión.', '[{"type":"heading","text":"Streaming estable con bajo ruido técnico"},{"type":"paragraph","text":"Demo publicado para probar guías técnicas de transmisión."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'tech', 'published', ARRAY['tech','streaming','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('tech-infra-demo-03', 'Infraestructura simple para crecer', 'Demo publicado para validar noticias sobre hosting, DNS y despliegues.', '[{"type":"heading","text":"Infraestructura simple para crecer"},{"type":"paragraph","text":"Demo publicado para validar noticias sobre hosting, DNS y despliegues."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'tech', 'published', ARRAY['tech','web','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('tech-security-demo-04', 'Seguridad básica para creadores', 'Demo publicado para probar contenido de cuentas, 2FA y backups.', '[{"type":"heading","text":"Seguridad básica para creadores"},{"type":"paragraph","text":"Demo publicado para probar contenido de cuentas, 2FA y backups."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'tech', 'published', ARRAY['tech','security','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('tech-systems-demo-05', 'Windows, Linux y herramientas híbridas', 'Demo publicado para validar software y productividad.', '[{"type":"heading","text":"Windows, Linux y herramientas híbridas"},{"type":"paragraph","text":"Demo publicado para validar software y productividad."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'tech', 'published', ARRAY['tech','systems','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('fun-memes-demo-01', 'Memes rápidos: cuando el build falla', 'Demo publicado para probar la rama Memes y humor de comunidad.', '[{"type":"heading","text":"Memes rápidos: cuando el build falla"},{"type":"paragraph","text":"Demo publicado para probar la rama Memes y humor de comunidad."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'community', 'published', ARRAY['fun','memes','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('fun-clips-demo-02', 'Clips cortos para Reels, Shorts y Threads', 'Demo publicado para validar publicación de clips y videos.', '[{"type":"heading","text":"Clips cortos para Reels, Shorts y Threads"},{"type":"paragraph","text":"Demo publicado para validar publicación de clips y videos."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'community', 'published', ARRAY['fun','clips','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('fun-wisp-demo-03', 'El Wisp aparece donde quiere', 'Demo publicado para probar humor narrativo del ecosistema.', '[{"type":"heading","text":"El Wisp aparece donde quiere"},{"type":"paragraph","text":"Demo publicado para probar humor narrativo del ecosistema."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'community', 'published', ARRAY['fun','wisp','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('fun-legends-demo-04', 'Leyendas digitales y rarezas gamer', 'Demo publicado para validar historias raras sin presentarlas como hechos.', '[{"type":"heading","text":"Leyendas digitales y rarezas gamer"},{"type":"paragraph","text":"Demo publicado para validar historias raras sin presentarlas como hechos."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'community', 'published', ARRAY['fun','legends','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('fun-lore-demo-05', 'Cuando el meme se vuelve lore', 'Demo publicado para medir identidad, humor y continuidad de marca.', '[{"type":"heading","text":"Cuando el meme se vuelve lore"},{"type":"paragraph","text":"Demo publicado para medir identidad, humor y continuidad de marca."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'community', 'published', ARRAY['fun','lore','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('green-linux-demo-01', 'Linux básico para entrar al Green Node', 'Demo publicado para probar contenido educativo del nodo verde.', '[{"type":"heading","text":"Linux básico para entrar al Green Node"},{"type":"paragraph","text":"Demo publicado para probar contenido educativo del nodo verde."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'green', 'published', ARRAY['green','linux','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('green-privacy-demo-02', 'Privacidad digital para creadores', 'Demo publicado para validar higiene digital, cuentas y 2FA.', '[{"type":"heading","text":"Privacidad digital para creadores"},{"type":"paragraph","text":"Demo publicado para validar higiene digital, cuentas y 2FA."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'green', 'published', ARRAY['green','privacy','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('green-osint-demo-03', 'Investigación documental con fuentes públicas', 'Demo publicado para probar OSINT educativo y límites seguros.', '[{"type":"heading","text":"Investigación documental con fuentes públicas"},{"type":"paragraph","text":"Demo publicado para probar OSINT educativo y límites seguros."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'green', 'published', ARRAY['green','research','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('green-backup-demo-04', 'Backups antes de experimentar', 'Demo publicado para validar buenas prácticas defensivas.', '[{"type":"heading","text":"Backups antes de experimentar"},{"type":"paragraph","text":"Demo publicado para validar buenas prácticas defensivas."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'green', 'published', ARRAY['green','backup','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('green-open-demo-05', 'Open source como ruta de aprendizaje', 'Demo publicado para probar cultura libre y herramientas abiertas.', '[{"type":"heading","text":"Open source como ruta de aprendizaje"},{"type":"paragraph","text":"Demo publicado para probar cultura libre y herramientas abiertas."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'green', 'published', ARRAY['green','opensource','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('programming-react-demo-01', 'React sin humo para proyectos reales', 'Demo publicado para probar contenido de programación web.', '[{"type":"heading","text":"React sin humo para proyectos reales"},{"type":"paragraph","text":"Demo publicado para probar contenido de programación web."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'programming', 'published', ARRAY['programming','react','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('programming-git-demo-02', 'Git como línea de tiempo del proyecto', 'Demo publicado para validar ramas, commits y recuperación.', '[{"type":"heading","text":"Git como línea de tiempo del proyecto"},{"type":"paragraph","text":"Demo publicado para validar ramas, commits y recuperación."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'programming', 'published', ARRAY['programming','git','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('programming-api-demo-03', 'APIs para conectar el ecosistema', 'Demo publicado para probar contenido técnico aplicado.', '[{"type":"heading","text":"APIs para conectar el ecosistema"},{"type":"paragraph","text":"Demo publicado para probar contenido técnico aplicado."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'programming', 'published', ARRAY['programming','api','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('programming-scripts-demo-04', 'Scripts útiles para creadores', 'Demo publicado para validar automatización simple y defensiva.', '[{"type":"heading","text":"Scripts útiles para creadores"},{"type":"paragraph","text":"Demo publicado para validar automatización simple y defensiva."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'programming', 'published', ARRAY['programming','scripts','demo'], ARRAY[]::text[], false, 'approved', now()),
  ('programming-docs-demo-05', 'Documentar para que otra IA entienda', 'Demo publicado para probar documentación y fuente única de verdad.', '[{"type":"heading","text":"Documentar para que otra IA entienda"},{"type":"paragraph","text":"Demo publicado para probar documentación y fuente única de verdad."},{"type":"paragraph","text":"Contenido demo generado para probar el publicador automático de XETHKIOZ. Reemplazar por noticia real antes de promoción externa."}]'::jsonb, 'programming', 'published', ARRAY['programming','docs','demo'], ARRAY[]::text[], false, 'approved', now())
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  content = EXCLUDED.content,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  tags = EXCLUDED.tags,
  review_status = EXCLUDED.review_status,
  published_at = EXCLUDED.published_at,
  updated_at = now();
