extends Node

signal toast_requested(message: String)
signal dialog_requested(speaker: String, text: String)
signal npc_interacted(npc_id: String)
signal lore_discovered(lore_id: String, title: String, discovered_count: int, total_hint: int)
signal poi_discovered(poi_id: String, display_name: String, discovered_count: int, xp_reward: int)
signal familiar_captured(species_id: String, display_name: String)
signal familiar_assessed(species_id: String, affinity: String, mentor_id: String)
signal familiar_trained(species_id: String, rank: int, mentor_id: String)
signal active_familiar_changed(species_id: String)
signal player_health_changed(current: float, maximum: float)
signal player_mana_changed(current: float, maximum: float)
signal player_progress_changed(level: int, xp: int, xp_to_next: int)
signal currency_changed(crystals: int)
signal inventory_changed(stacks: Dictionary)
signal set_progress_changed(set_id: String, pieces: int)
signal enemy_defeated(enemy_id: String, xp_reward: int, world_position: Vector2)
signal boss_phase_changed(boss_id: String, phase: int)
signal quest_changed(title: String, objective: String, completed: bool)
signal demo_stage_changed(stage_id: String)
signal mentor_selected(mentor_id: String)
signal traversal_unlocked(traversal_id: String)
signal weather_changed(weather_id: String)
signal time_changed(hour: float)
signal pet_bond_changed(bond: int)
signal world_flag_changed(flag_id: String, value: bool)
signal xethkioz_tail_stage_changed(tails: int)
